import 'package:flutter/material.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:luma/features/plugins/installed/ai_detector/ai_detector_page.dart';
import 'package:luma/theme/luma_theme.dart';
import 'package:luma/theme/theme_style.dart';

/// Long enough to clear the 25-word minimum, and carrying three zero-width
/// spaces so the watermark scan has something conclusive to find.
const _signed =
    'The​quarterly review covers every region we operate in this year, and '
    'the​ margin held steady throughout. Nothing in the numbers moved far '
    'enough to​ change the outlook we published back in the spring.';

/// Same length, no hidden characters, no stock phrasing.
const _plain =
    'The quarterly review covers every region we operate in this year, and '
    'the margin held steady throughout. Nothing in the numbers moved far '
    'enough to change the outlook we published back in the spring.';

Widget _wrap(Widget child) => MaterialApp(
      theme: LumaTheme.from(Brightness.dark, null, LumaThemeStyle.standard),
      home: child,
    );

Future<void> _review(WidgetTester tester, String text) async {
  await tester.pumpWidget(_wrap(const AiDetectorPage()));
  await tester.enterText(find.byType(TextField), text);
  await tester.pump();
  await tester.ensureVisible(find.text('Review'));
  await tester.pumpAndSettle();
  await tester.tap(find.text('Review'));
  await tester.pumpAndSettle();
}

void main() {
  group('AiDetectorPage', () {
    testWidgets('Review stays inert until the minimum word count is met',
        (tester) async {
      await tester.pumpWidget(_wrap(const AiDetectorPage()));
      expect(find.textContaining('of 25 words'), findsOneWidget);

      await tester.enterText(find.byType(TextField), 'too short');
      await tester.pump();
      await tester.tap(find.text('Review'));
      await tester.pumpAndSettle();
      // No verdict card appeared.
      expect(find.text('AI-likelihood'), findsNothing);

      await tester.enterText(find.byType(TextField), _plain);
      await tester.pump();
      expect(find.textContaining('words ready to review'), findsOneWidget);
    });

    testWidgets('a watermarked paste is attributed to Claude',
        (tester) async {
      await _review(tester, _signed);
      expect(find.text('Generated by Claude'), findsOneWidget);
      expect(find.text('Watermark match'), findsOneWidget);
      expect(find.text('Claude watermark'), findsOneWidget);
    });

    testWidgets('clean text is not attributed to anyone', (tester) async {
      await _review(tester, _plain);
      expect(find.text('Generated by Claude'), findsNothing);
      expect(find.textContaining('human'), findsWidgets);
    });

    testWidgets('the highlights tab paints the source and lists a legend',
        (tester) async {
      await _review(tester, _signed);
      expect(find.byType(SelectableText), findsOneWidget);

      final painted = tester.widget<SelectableText>(
        find.byType(SelectableText),
      );
      final spans = (painted.textSpan!).children!.cast<TextSpan>();
      // At least one span is styled as a highlight rather than plain text.
      expect(
        spans.any((s) => s.style?.backgroundColor != null),
        isTrue,
      );
      // Reassembling the spans must give back the original text untouched.
      expect(spans.map((s) => s.text).join(), _signed);
    });

    testWidgets('switching to Signals shows the fired checks', (tester) async {
      await _review(tester, _signed);
      // The tab strip sits below the fold on the 800x600 test surface.
      await tester.ensureVisible(find.textContaining('Signals'));
      await tester.pumpAndSettle();
      await tester.tap(find.textContaining('Signals'));
      await tester.pumpAndSettle();
      expect(find.text('Claude watermark found'), findsOneWidget);
      expect(find.text('Quiet checks'), findsOneWidget);
      expect(find.byType(SelectableText), findsNothing);
    });

    testWidgets('the verdict stacks instead of overflowing on a phone',
        (tester) async {
      tester.view.physicalSize = const Size(360, 780);
      tester.view.devicePixelRatio = 1;
      addTearDown(tester.view.reset);
      await _review(tester, _signed);
      expect(tester.takeException(), isNull);
      expect(find.text('Generated by Claude'), findsOneWidget);
      // The gauge sits above the headline rather than beside it.
      final gauge = tester.getRect(find.text('AI-likelihood'));
      final headline = tester.getRect(find.text('Generated by Claude'));
      expect(gauge.bottom, lessThan(headline.top));
    });

    testWidgets('Clear resets back to the empty state', (tester) async {
      await _review(tester, _signed);
      expect(find.text('Generated by Claude'), findsOneWidget);
      await tester.tap(find.text('Clear'));
      await tester.pumpAndSettle();
      expect(find.text('Generated by Claude'), findsNothing);
      expect(find.textContaining('of 25 words'), findsOneWidget);
    });
  });
}
