// GENERATED by tool/mc_data/generate.dart from Minecraft 26.3 game
// data. Do not edit by hand — rerun the generator instead.

import 'mc_data_types.dart';

/// The superflat presets the world screen offers.
const List<McFlatPreset> kMcFlatPresets = [
  McFlatPreset(
    id: 'classic_flat',
    icon: 'grass_block',
    biome: 'plains',
    features: false,
    lakes: false,
    structures: ['villages'],
    layers: [McFlatLayer('bedrock', 1), McFlatLayer('dirt', 2), McFlatLayer('grass_block', 1)],
  ),
  McFlatPreset(
    id: 'tunnelers_dream',
    icon: 'stone',
    biome: 'windswept_hills',
    features: true,
    lakes: false,
    structures: ['mineshafts', 'strongholds'],
    layers: [McFlatLayer('bedrock', 1), McFlatLayer('stone', 230), McFlatLayer('dirt', 5), McFlatLayer('grass_block', 1)],
  ),
  McFlatPreset(
    id: 'water_world',
    icon: 'water_bucket',
    biome: 'deep_ocean',
    features: false,
    lakes: false,
    structures: ['ocean_monuments', 'ocean_ruins', 'shipwrecks'],
    layers: [McFlatLayer('bedrock', 1), McFlatLayer('deepslate', 64), McFlatLayer('stone', 5), McFlatLayer('dirt', 5), McFlatLayer('gravel', 5), McFlatLayer('water', 90)],
  ),
  McFlatPreset(
    id: 'overworld',
    icon: 'short_grass',
    biome: 'plains',
    features: true,
    lakes: true,
    structures: ['mineshafts', 'pillager_outposts', 'ruined_portals', 'strongholds', 'villages'],
    layers: [McFlatLayer('bedrock', 1), McFlatLayer('stone', 59), McFlatLayer('dirt', 3), McFlatLayer('grass_block', 1)],
  ),
  McFlatPreset(
    id: 'snowy_kingdom',
    icon: 'snow',
    biome: 'snowy_plains',
    features: false,
    lakes: false,
    structures: ['igloos', 'villages'],
    layers: [McFlatLayer('bedrock', 1), McFlatLayer('stone', 59), McFlatLayer('dirt', 3), McFlatLayer('grass_block', 1), McFlatLayer('snow', 1)],
  ),
  McFlatPreset(
    id: 'bottomless_pit',
    icon: 'feather',
    biome: 'plains',
    features: false,
    lakes: false,
    structures: ['villages'],
    layers: [McFlatLayer('cobblestone', 2), McFlatLayer('dirt', 3), McFlatLayer('grass_block', 1)],
  ),
  McFlatPreset(
    id: 'desert',
    icon: 'sand',
    biome: 'desert',
    features: true,
    lakes: false,
    structures: ['desert_pyramids', 'mineshafts', 'strongholds', 'villages'],
    layers: [McFlatLayer('bedrock', 1), McFlatLayer('stone', 3), McFlatLayer('sandstone', 52), McFlatLayer('sand', 8)],
  ),
  McFlatPreset(
    id: 'redstone_ready',
    icon: 'redstone',
    biome: 'desert',
    features: false,
    lakes: false,
    structures: [],
    layers: [McFlatLayer('bedrock', 1), McFlatLayer('stone', 3), McFlatLayer('sandstone', 116)],
  ),
  McFlatPreset(
    id: 'the_void',
    icon: 'barrier',
    biome: 'the_void',
    features: true,
    lakes: false,
    structures: [],
    layers: [McFlatLayer('air', 1)],
  ),
];
