// GENERATED by tool/mc_data/generate.dart from Minecraft 26.3 game
// data. Do not edit by hand — rerun the generator instead.

import 'mc_data_types.dart';

/// Every ore's placed features, as the world generator runs them.
const List<McOre> kMcOres = [
  McOre(id: 'coal', nether: false, placements: [
    McOrePlacement(feature: 'ore_coal_upper', perChunk: 30.0, trapezoid: false, minY: 136, maxY: 319, size: 17, airDiscard: 0.0),
    McOrePlacement(feature: 'ore_coal_lower', perChunk: 20.0, trapezoid: true, minY: 0, maxY: 192, size: 17, airDiscard: 0.5),
  ]),
  McOre(id: 'iron', nether: false, placements: [
    McOrePlacement(feature: 'ore_iron_upper', perChunk: 90.0, trapezoid: true, minY: 80, maxY: 384, size: 9, airDiscard: 0.0),
    McOrePlacement(feature: 'ore_iron_middle', perChunk: 10.0, trapezoid: true, minY: -24, maxY: 56, size: 9, airDiscard: 0.0),
    McOrePlacement(feature: 'ore_iron_small', perChunk: 10.0, trapezoid: false, minY: -64, maxY: 72, size: 4, airDiscard: 0.0),
  ]),
  McOre(id: 'copper', nether: false, placements: [
    McOrePlacement(feature: 'ore_copper', perChunk: 16.0, trapezoid: true, minY: -16, maxY: 112, size: 10, airDiscard: 0.0),
    McOrePlacement(feature: 'ore_copper_large', perChunk: 16.0, trapezoid: true, minY: -16, maxY: 112, size: 20, airDiscard: 0.0, biome: 'dripstone_caves'),
  ]),
  McOre(id: 'gold', nether: false, placements: [
    McOrePlacement(feature: 'ore_gold', perChunk: 4.0, trapezoid: true, minY: -64, maxY: 32, size: 9, airDiscard: 0.5),
    McOrePlacement(feature: 'ore_gold_lower', perChunk: 0.5, trapezoid: false, minY: -64, maxY: -48, size: 9, airDiscard: 0.5),
    McOrePlacement(feature: 'ore_gold_extra', perChunk: 50.0, trapezoid: false, minY: 32, maxY: 256, size: 9, airDiscard: 0.0, biome: 'badlands'),
  ]),
  McOre(id: 'redstone', nether: false, placements: [
    McOrePlacement(feature: 'ore_redstone', perChunk: 4.0, trapezoid: false, minY: -64, maxY: 15, size: 8, airDiscard: 0.0),
    McOrePlacement(feature: 'ore_redstone_lower', perChunk: 8.0, trapezoid: true, minY: -96, maxY: -32, size: 8, airDiscard: 0.0),
  ]),
  McOre(id: 'lapis', nether: false, placements: [
    McOrePlacement(feature: 'ore_lapis', perChunk: 2.0, trapezoid: true, minY: -32, maxY: 32, size: 7, airDiscard: 0.0),
    McOrePlacement(feature: 'ore_lapis_buried', perChunk: 4.0, trapezoid: false, minY: -64, maxY: 64, size: 7, airDiscard: 1.0),
  ]),
  McOre(id: 'diamond', nether: false, placements: [
    McOrePlacement(feature: 'ore_diamond', perChunk: 7.0, trapezoid: true, minY: -144, maxY: 16, size: 4, airDiscard: 0.5),
    McOrePlacement(feature: 'ore_diamond_medium', perChunk: 2.0, trapezoid: false, minY: -64, maxY: -4, size: 8, airDiscard: 0.5),
    McOrePlacement(feature: 'ore_diamond_large', perChunk: 0.1111, trapezoid: true, minY: -144, maxY: 16, size: 12, airDiscard: 0.7),
    McOrePlacement(feature: 'ore_diamond_buried', perChunk: 4.0, trapezoid: true, minY: -144, maxY: 16, size: 8, airDiscard: 1.0),
  ]),
  McOre(id: 'emerald', nether: false, placements: [
    McOrePlacement(feature: 'ore_emerald', perChunk: 100.0, trapezoid: true, minY: -16, maxY: 480, size: 3, airDiscard: 0.0, biome: 'mountains'),
  ]),
  McOre(id: 'nether_quartz', nether: true, placements: [
    McOrePlacement(feature: 'ore_quartz_nether', perChunk: 16.0, trapezoid: false, minY: 10, maxY: 117, size: 14, airDiscard: 0.0),
    McOrePlacement(feature: 'ore_quartz_deltas', perChunk: 32.0, trapezoid: false, minY: 10, maxY: 117, size: 14, airDiscard: 0.0, biome: 'basalt_deltas'),
  ]),
  McOre(id: 'nether_gold', nether: true, placements: [
    McOrePlacement(feature: 'ore_gold_nether', perChunk: 10.0, trapezoid: false, minY: 10, maxY: 117, size: 10, airDiscard: 0.0),
    McOrePlacement(feature: 'ore_gold_deltas', perChunk: 20.0, trapezoid: false, minY: 10, maxY: 117, size: 10, airDiscard: 0.0, biome: 'basalt_deltas'),
  ]),
  McOre(id: 'ancient_debris', nether: true, placements: [
    McOrePlacement(feature: 'ore_ancient_debris_large', perChunk: 1.0, trapezoid: true, minY: 8, maxY: 24, size: 3, airDiscard: 1.0),
    McOrePlacement(feature: 'ore_debris_small', perChunk: 1.0, trapezoid: false, minY: 8, maxY: 119, size: 2, airDiscard: 1.0),
  ]),
];
