// Regenerates the Minecraft tables under
// lib/features/plugins/installed/game_tools/minecraft/data/ from the game's
// own data, as published by misode/mcmeta.
//
//   curl -L -o data.zip https://codeload.github.com/misode/mcmeta/zip/refs/tags/26.3-data
//   curl -L -o registries.json https://raw.githubusercontent.com/misode/mcmeta/26.3-summary/registries/data.min.json
//   dart run tool/mc_data/generate.dart data.zip registries.json 26.3
//
// Only ids, numbers and tag memberships are read — no Mojang textures,
// sounds or text ever end up in the repo.
import 'dart:convert';
import 'dart:io';

import 'package:archive/archive.dart';

late Map<String, ArchiveFile> _files;
late String _root;

const _out = 'lib/features/plugins/installed/game_tools/minecraft/data';

void main(List<String> args) {
  if (args.length < 3) {
    stderr.writeln(
      'usage: dart run tool/mc_data/generate.dart <data.zip> <registries.json> <version>',
    );
    exit(64);
  }
  final archive = ZipDecoder().decodeBytes(File(args[0]).readAsBytesSync());
  _files = {for (final f in archive.files) f.name: f};
  _root = _files.keys
      .firstWhere((n) => n.endsWith('/data/minecraft/'))
      .replaceFirst(RegExp(r'data/minecraft/$'), '');
  final registries =
      jsonDecode(File(args[1]).readAsStringSync()) as Map<String, dynamic>;
  final version = args[2];

  _writeRegistries(registries, version);
  _writeVillagers(registries, version);
  _writeSulfurCube(version);
  _writeFlatPresets(registries, version);
  _writeOres(version);
}

String _header(String version) =>
    '// GENERATED by tool/mc_data/generate.dart from Minecraft $version game\n'
    '// data. Do not edit by hand — rerun the generator instead.\n\n';

Map<String, dynamic>? _json(String path) {
  final file = _files['${_root}data/minecraft/$path'];
  if (file == null) return null;
  return jsonDecode(utf8.decode(file.content as List<int>))
      as Map<String, dynamic>;
}

String _strip(String id) => id.replaceFirst('minecraft:', '');

String _q(String s) => "'${s.replaceAll(r'\', r'\\').replaceAll("'", r"\'")}'";

String _list(Iterable<String> values) =>
    '[\n${values.map((v) => '  ${_q(v)},').join('\n')}\n]';

String _num(num n) {
  if (n is int || n == n.roundToDouble()) {
    final s = n.toDouble().toString();
    return s.endsWith('.0') ? s : s;
  }
  final rounded = double.parse(n.toStringAsFixed(4));
  return rounded.toString();
}

void _write(String name, String body) {
  final file = File('$_out/$name');
  file.parent.createSync(recursive: true);
  file.writeAsStringSync(body);
  stdout.writeln('wrote ${file.path}');
}

// ─── Registries ──────────────────────────────────────────────────────────────

void _writeRegistries(Map<String, dynamic> r, String version) {
  List<String> reg(String key) =>
      ((r[key] as List?) ?? const []).cast<String>().toList()..sort();

  const notSummonable = {
    'player',
    'fishing_bobber',
    'lightning_bolt',
    'marker',
    'item',
    'experience_orb',
    'area_effect_cloud',
    'leash_knot',
    'painting',
    'item_frame',
    'glow_item_frame',
    'evoker_fangs',
  };

  final b = StringBuffer(_header(version))
    ..writeln('/// The game version these tables were read from.')
    ..writeln("const String kMcDataVersion = '$version';")
    ..writeln()
    ..writeln('/// Every item id, without the `minecraft:` namespace.')
    ..writeln('const List<String> kMcItems = ${_list(reg('item'))};')
    ..writeln()
    ..writeln('/// Every block id.')
    ..writeln('const List<String> kMcBlocks = ${_list(reg('block'))};')
    ..writeln()
    ..writeln('/// Entity types /summon accepts.')
    ..writeln(
      'const List<String> kMcEntities = ${_list(reg('entity_type').where((e) => !notSummonable.contains(e)))};',
    )
    ..writeln()
    ..writeln('const List<String> kMcEffects = ${_list(reg('mob_effect'))};')
    ..writeln()
    ..writeln('const List<String> kMcPotions = ${_list(reg('potion'))};')
    ..writeln()
    ..writeln(
      'const List<String> kMcEnchantments = ${_list(reg('enchantment'))};',
    )
    ..writeln()
    ..writeln(
      'const List<String> kMcTrimPatterns = ${_list(reg('trim_pattern'))};',
    )
    ..writeln()
    ..writeln(
      'const List<String> kMcTrimMaterials = ${_list(reg('trim_material'))};',
    )
    ..writeln()
    ..writeln(
      'const List<String> kMcBannerPatterns = ${_list(reg('banner_pattern'))};',
    )
    ..writeln()
    ..writeln('const List<String> kMcBiomes = ${_list(reg('worldgen/biome'))};')
    ..writeln()
    ..writeln(
      'const List<String> kMcParticles = ${_list(reg('particle_type'))};',
    )
    ..writeln()
    ..writeln('const List<String> kMcAttributes = ${_list(reg('attribute'))};')
    ..writeln()
    ..writeln(
      'const List<String> kMcAdvancementTriggers = ${_list(reg('trigger_type'))};',
    )
    ..writeln()
    ..writeln('const List<String> kMcGameRules = ${_list(reg('game_rule'))};')
    ..writeln()
    ..writeln('const List<String> kMcSounds = ${_list(reg('sound_event'))};')
    ..writeln()
    ..writeln(
      'const List<String> kMcDamageTypes = ${_list(reg('damage_type'))};',
    );
  _write('mc_registries_data.dart', b.toString());
}

// ─── Villager trades ─────────────────────────────────────────────────────────

/// Expands a villager-trade tag to the trade ids it names, following nested
/// tags the way the game does.
List<String> _tradeTag(String tag) {
  final json = _json('tags/villager_trade/${_strip(tag)}.json');
  if (json == null) return const [];
  final out = <String>[];
  for (final v in (json['values'] as List)) {
    final id = v is String ? v : (v as Map)['id'] as String;
    if (id.startsWith('#')) {
      out.addAll(_tradeTag(id.substring(1)));
    } else {
      out.add(_strip(id));
    }
  }
  return out;
}

String _tradeLiteral(String id) {
  final t = _json('villager_trade/$id.json')!;
  final wants = t['wants'] as Map<String, dynamic>;
  final gives = t['gives'] as Map<String, dynamic>;
  final extra = t['additional_wants'] as Map<String, dynamic>?;
  final notes = <String>[];

  // Notes are codes the guide words in the reader's language:
  // `name` or `name:arg:arg`.
  var modifiers = t['given_item_modifier'];
  if (modifiers is Map) modifiers = [modifiers];
  for (final m in (modifiers as List? ?? const [])) {
    final mod = m as Map<String, dynamic>;
    switch (_strip(mod['type'] as String)) {
      case 'enchant_with_levels':
        final levels = mod['levels'];
        notes.add(
          levels is Map
              ? 'enchantLevels:${levels['min']}:${levels['max']}'
              : 'enchantLevels:$levels:$levels',
        );
      case 'enchant_randomly':
        notes.add('enchantRandom');
      case 'exploration_map':
        final target = (mod['decoration'] ?? mod['destination']) as String?;
        notes.add(
          target == null
              ? 'explorerMap'
              : 'map:${_strip(target).replaceAll('#', '')}',
        );
      case 'set_random_dyes':
        notes.add('dyes');
      case 'set_stew_effect':
        notes.add('stew');
      case 'set_random_potion':
        notes.add('randomPotion');
      case 'set_potion':
        notes.add('potion:${_strip(mod['id'] as String)}');
    }
  }
  if (t['double_trade_price_enchantments'] != null) {
    notes.add('treasureDouble');
  }
  final predicate = t['merchant_predicate'] as Map<String, dynamic>?;
  final variants =
      ((predicate?['predicate'] as Map?)?['minecraft:predicates']
          as Map?)?['minecraft:villager/variant'];
  if (variants is List) {
    notes.add('variants:${variants.map((v) => _strip(v as String)).join(',')}');
  }
  final wantsCount = (wants['count'] as num?)?.toInt() ?? 1;
  if (wantsCount == 0) notes.add('priceScales');

  final parts = <String>[
    'id: ${_q(id)}',
    'wants: ${_q(_strip(wants['id'] as String))}',
    if (wantsCount != 1) 'wantsCount: $wantsCount',
    if (extra != null) 'extra: ${_q(_strip(extra['id'] as String))}',
    if (extra != null && extra['count'] != null)
      'extraCount: ${(extra['count'] as num).toInt()}',
    'gives: ${_q(_strip(gives['id'] as String))}',
    if (gives['count'] != null) 'givesCount: ${(gives['count'] as num).toInt()}',
    if (t['max_uses'] != null) 'maxUses: ${(t['max_uses'] as num).toInt()}',
    if (t['xp'] != null) 'xp: ${(t['xp'] as num).toInt()}',
    if (notes.isNotEmpty) 'notes: ${'[${notes.map(_q).join(', ')}]'}',
  ];
  return 'McTrade(${parts.join(', ')})';
}

void _writeVillagers(Map<String, dynamic> r, String version) {
  final sets = ((r['trade_set'] as List?) ?? const []).cast<String>();
  final byOwner = <String, List<String>>{};
  for (final set in sets) {
    final slash = set.indexOf('/');
    byOwner.putIfAbsent(set.substring(0, slash), () => []).add(set);
  }

  final b = StringBuffer(_header(version))
    ..writeln("import 'mc_data_types.dart';")
    ..writeln()
    ..writeln(
      '/// Every villager profession\'s trade pools, plus the wandering trader\'s.',
    )
    ..writeln('const List<McTradeOwner> kMcVillagerTrades = [');
  final owners = byOwner.keys.toList()..sort();
  for (final owner in owners) {
    b.writeln('  McTradeOwner(id: ${_q(owner)}, pools: [');
    for (final set in byOwner[owner]!) {
      final json = _json('trade_set/$set.json')!;
      final picks = (json['amount'] as num).toInt();
      final ids = _tradeTag((json['trades'] as String).substring(1));
      b.writeln(
        '    McTradePool(id: ${_q(set.substring(owner.length + 1))}, picks: $picks, trades: [',
      );
      for (final id in ids) {
        b.writeln('      ${_tradeLiteral(id)},');
      }
      b.writeln('    ]),');
    }
    b.writeln('  ]),');
  }
  b.writeln('];');
  _write('villager_trades_data.dart', b.toString());
}

// ─── Sulfur cube ─────────────────────────────────────────────────────────────

List<String> _itemTag(String tag, [Set<String>? seen]) {
  seen ??= <String>{};
  if (!seen.add(tag)) return const [];
  final json = _json('tags/item/${_strip(tag)}.json');
  if (json == null) return const [];
  final out = <String>[];
  for (final v in (json['values'] as List)) {
    final id = v is String ? v : (v as Map)['id'] as String;
    if (id.startsWith('#')) {
      out.addAll(_itemTag(id.substring(1), seen));
    } else {
      out.add(_strip(id));
    }
  }
  return out;
}

void _writeSulfurCube(String version) {
  const order = [
    'regular',
    'bouncy',
    'slow_bouncy',
    'slow_flat',
    'fast_flat',
    'light',
    'fast_sliding',
    'slow_sliding',
    'high_resistance',
    'sticky',
    'explosive',
    'hot',
  ];
  final b = StringBuffer(_header(version))
    ..writeln("import 'mc_data_types.dart';")
    ..writeln()
    ..writeln('/// The twelve behaviours a sulfur cube takes on from the block it')
    ..writeln('/// swallowed, in the order the guide lists them.')
    ..writeln('const List<McCubeArchetype> kMcCubeArchetypes = [');
  for (final id in order) {
    final a = _json('sulfur_cube_archetype/$id.json')!;
    double mod(String attribute) {
      for (final m in (a['attribute_modifiers'] as List? ?? const [])) {
        if (_strip((m as Map)['attribute'] as String) == attribute) {
          return (m['amount'] as num).toDouble();
        }
      }
      return 0;
    }

    final tag = (a['items'] as String).substring(1);
    final tagJson = _json('tags/item/${_strip(tag)}.json')!;
    final groups = <String>[
      for (final v in tagJson['values'] as List)
        if ((v as String).startsWith('#')) _strip(v.substring(1)),
    ];
    final blocks = _itemTag(tag).toSet().toList()..sort();
    final kb = a['knockback_modifiers'] as Map<String, dynamic>;
    final sound = a['sound_settings'] as Map<String, dynamic>;
    final explosion = a['explosion'] as Map<String, dynamic>?;
    final contact = a['contact_damage'] as Map<String, dynamic>?;
    b.writeln('  McCubeArchetype(');
    b.writeln('    id: ${_q(id)},');
    b.writeln('    buoyant: ${a['buoyant'] == true},');
    b.writeln('    knockbackResistance: ${_num(mod('knockback_resistance'))},');
    b.writeln('    bounciness: ${_num(mod('bounciness'))},');
    b.writeln('    friction: ${_num(mod('friction_modifier'))},');
    b.writeln('    airDrag: ${_num(mod('air_drag_modifier'))},');
    b.writeln(
      '    knockbackHorizontal: ${_num(kb['horizontal_power'] as num)},',
    );
    b.writeln('    knockbackVertical: ${_num(kb['vertical_power'] as num)},');
    b.writeln(
      '    pushCooldown: ${_num(sound['push_sound_cooldown'] as num)},',
    );
    if (explosion != null) {
      b.writeln(
        '    explosionPower: ${_num(explosion['power'] as num)},',
      );
      b.writeln('    explosionFuse: ${(explosion['fuse'] as num).toInt()},');
      b.writeln('    explosionFire: ${explosion['causes_fire'] == true},');
    }
    if (contact != null) {
      b.writeln('    contactDamage: ${_num(contact['amount'] as num)},');
    }
    b.writeln('    groups: [${groups.map(_q).join(', ')}],');
    b.writeln('    blocks: [${blocks.map(_q).join(', ')}],');
    b.writeln('  ),');
  }
  b.writeln('];');

  final immune = _json('tags/damage_type/sulfur_cube_with_block_immune_to.json')!;
  b
    ..writeln()
    ..writeln('/// Damage types a cube shrugs off while it holds a block.')
    ..writeln(
      'const List<String> kMcCubeImmunities = ${_list((immune['values'] as List).cast<String>().where((v) => !v.startsWith('#')).map(_strip))};',
    );
  _write('sulfur_cube_data.dart', b.toString());
}

// ─── Flat presets ────────────────────────────────────────────────────────────

void _writeFlatPresets(Map<String, dynamic> r, String version) {
  final ids =
      ((r['worldgen/flat_level_generator_preset'] as List?) ?? const [])
          .cast<String>();
  const order = [
    'classic_flat',
    'tunnelers_dream',
    'water_world',
    'overworld',
    'snowy_kingdom',
    'bottomless_pit',
    'desert',
    'redstone_ready',
    'the_void',
  ];
  final sorted = [
    ...order.where(ids.contains),
    ...ids.where((i) => !order.contains(i)),
  ];
  final b = StringBuffer(_header(version))
    ..writeln("import 'mc_data_types.dart';")
    ..writeln()
    ..writeln('/// The superflat presets the world screen offers.')
    ..writeln('const List<McFlatPreset> kMcFlatPresets = [');
  for (final id in sorted) {
    final p = _json('worldgen/flat_level_generator_preset/$id.json')!;
    final s = p['settings'] as Map<String, dynamic>;
    final layers = [
      for (final l in s['layers'] as List)
        'McFlatLayer(${_q(_strip((l as Map)['block'] as String))}, ${(l['height'] as num).toInt()})',
    ];
    var structures = s['structure_overrides'];
    if (structures is String) structures = [structures];
    b
      ..writeln('  McFlatPreset(')
      ..writeln('    id: ${_q(id)},')
      ..writeln('    icon: ${_q(_strip(p['display'] as String))},')
      ..writeln('    biome: ${_q(_strip(s['biome'] as String))},')
      ..writeln('    features: ${s['features'] == true},')
      ..writeln('    lakes: ${s['lakes'] == true},')
      ..writeln(
        '    structures: [${(structures as List? ?? const []).map((v) => _q(_strip(v as String))).join(', ')}],',
      )
      ..writeln('    layers: [${layers.join(', ')}],')
      ..writeln('  ),');
  }
  b.writeln('];');
  _write('flat_presets_data.dart', b.toString());
}

// ─── Ores ────────────────────────────────────────────────────────────────────

void _writeOres(String version) {
  // ore → (placed feature, where it applies). The biome-only features are
  // kept but labelled, since a best-Y figure for "anywhere" must not count
  // the badlands gold band.
  const ores = <String, List<(String, String?)>>{
    'coal': [('ore_coal_upper', null), ('ore_coal_lower', null)],
    'iron': [
      ('ore_iron_upper', null),
      ('ore_iron_middle', null),
      ('ore_iron_small', null),
    ],
    'copper': [
      ('ore_copper', null),
      ('ore_copper_large', 'dripstone_caves'),
    ],
    'gold': [
      ('ore_gold', null),
      ('ore_gold_lower', null),
      ('ore_gold_extra', 'badlands'),
    ],
    'redstone': [('ore_redstone', null), ('ore_redstone_lower', null)],
    'lapis': [('ore_lapis', null), ('ore_lapis_buried', null)],
    'diamond': [
      ('ore_diamond', null),
      ('ore_diamond_medium', null),
      ('ore_diamond_large', null),
      ('ore_diamond_buried', null),
    ],
    'emerald': [('ore_emerald', 'mountains')],
    'nether_quartz': [
      ('ore_quartz_nether', null),
      ('ore_quartz_deltas', 'basalt_deltas'),
    ],
    'nether_gold': [
      ('ore_gold_nether', null),
      ('ore_gold_deltas', 'basalt_deltas'),
    ],
    'ancient_debris': [
      ('ore_ancient_debris_large', null),
      ('ore_debris_small', null),
    ],
  };

  int anchor(Map<String, dynamic> a, bool nether) {
    const bottom = -64, top = 319, netherBottom = 0, netherTop = 127;
    final lo = nether ? netherBottom : bottom;
    final hi = nether ? netherTop : top;
    if (a.containsKey('absolute')) return (a['absolute'] as num).toInt();
    if (a.containsKey('above_bottom')) {
      return lo + (a['above_bottom'] as num).toInt();
    }
    return hi - (a['below_top'] as num).toInt();
  }

  final b = StringBuffer(_header(version))
    ..writeln("import 'mc_data_types.dart';")
    ..writeln()
    ..writeln('/// Every ore\'s placed features, as the world generator runs them.')
    ..writeln('const List<McOre> kMcOres = [');
  for (final entry in ores.entries) {
    final nether = entry.key.startsWith('nether') ||
        entry.key == 'ancient_debris';
    b.writeln(
      '  McOre(id: ${_q(entry.key)}, nether: $nether, placements: [',
    );
    for (final (featureId, biome) in entry.value) {
      final placed = _json('worldgen/placed_feature/$featureId.json')!;
      final feature = _json(
        'worldgen/feature/${_strip(placed['feature'] as String)}.json',
      )!;
      var perChunk = 1.0;
      Map<String, dynamic>? height;
      for (final p in placed['placement'] as List) {
        final step = p as Map<String, dynamic>;
        switch (_strip(step['type'] as String)) {
          case 'count':
            final count = step['count'];
            perChunk = count is num
                ? count.toDouble()
                : ((count['min_inclusive'] as num) +
                          (count['max_inclusive'] as num)) /
                      2;
          case 'rarity_filter':
            perChunk = 1 / (step['chance'] as num);
          case 'height_range':
            height = step['height'] as Map<String, dynamic>;
        }
      }
      final shape = _strip(height!['type'] as String);
      final min = anchor(height['min_inclusive'] as Map<String, dynamic>, nether);
      final max = anchor(height['max_inclusive'] as Map<String, dynamic>, nether);
      b.writeln(
        '    McOrePlacement(feature: ${_q(featureId)}, perChunk: ${_num(perChunk)}, '
        'trapezoid: ${shape == 'trapezoid'}, minY: $min, maxY: $max, '
        'size: ${(feature['size'] as num).toInt()}, '
        'airDiscard: ${_num((feature['discard_chance_on_air_exposure'] as num?) ?? 0)}'
        '${biome == null ? '' : ', biome: ${_q(biome)}'}),',
      );
    }
    b.writeln('  ]),');
  }
  b.writeln('];');
  _write('ores_data.dart', b.toString());
}
