import 'dart:io';

import 'package:file_picker/file_picker.dart';
import 'package:flutter/material.dart';
import 'package:open_file/open_file.dart';

import '../../../theme/luma_theme.dart';
import '../data/chat_repository.dart';

Future<void> openAssistantArtifact(BuildContext context, String path) async {
  String? error;
  try {
    if (!await File(path).exists()) {
      error = 'This file is no longer on this device.';
    } else {
      final result = await OpenFile.open(path);
      if (result.type != ResultType.done) error = result.message;
    }
  } catch (failure) {
    error = 'Could not open the file: $failure';
  }
  if (error != null && context.mounted) {
    ScaffoldMessenger.of(context).showSnackBar(SnackBar(content: Text(error)));
  }
}

class AssistantArtifactsView extends StatefulWidget {
  const AssistantArtifactsView({
    super.key,
    required this.repository,
    required this.onOpenChat,
  });
  final ChatRepository repository;
  final ValueChanged<int> onOpenChat;
  @override
  State<AssistantArtifactsView> createState() => _AssistantArtifactsViewState();
}

class _AssistantArtifactsViewState extends State<AssistantArtifactsView> {
  late final Future<void> _indexed = widget.repository.indexExistingArtifacts();
  String _query = '';
  String _filter = 'All';
  @override
  Widget build(BuildContext context) => FutureBuilder<void>(
    future: _indexed,
    builder: (context, indexed) => StreamBuilder<List<ChatArtifactRecord>>(
      stream: widget.repository.watchArtifacts(),
      builder: (context, snapshot) {
        final files = (snapshot.data ?? const <ChatArtifactRecord>[])
            .where(
              (file) =>
                  file.name.toLowerCase().contains(_query) &&
                  (_filter == 'All' ||
                      (_filter == 'Images') ==
                          file.mimeType.startsWith('image/')),
            )
            .toList();
        return ListView(
          padding: const EdgeInsets.all(24),
          children: [
            Text(
              'Artifacts',
              style: TextStyle(
                fontSize: 27,
                fontWeight: FontWeight.w600,
                color: context.luma.textPrimary,
              ),
            ),
            const SizedBox(height: 10),
            Text(
              'Files and pictures generated by the assistant in Luma.',
              style: TextStyle(color: context.luma.textSecondary),
            ),
            const SizedBox(height: 20),
            TextField(
              onChanged: (value) =>
                  setState(() => _query = value.toLowerCase().trim()),
              decoration: const InputDecoration(
                prefixIcon: Icon(Icons.search_rounded),
                hintText: 'Search artifacts',
              ),
            ),
            const SizedBox(height: 12),
            Wrap(
              spacing: 8,
              children: [
                for (final filter in ['All', 'Images', 'Files'])
                  ChoiceChip(
                    label: Text(filter),
                    selected: _filter == filter,
                    onSelected: (_) => setState(() => _filter = filter),
                  ),
              ],
            ),
            const SizedBox(height: 20),
            if (snapshot.hasError || indexed.hasError)
              const Text('Could not load artifacts.'),
            if (!snapshot.hasData) const LinearProgressIndicator(),
            if (snapshot.hasData && files.isEmpty)
              const Padding(
                padding: EdgeInsets.symmetric(vertical: 30),
                child: Text(
                  'No artifacts found. Generated files and pictures will appear here.',
                ),
              ),
            for (final file in files)
              Card(
                child: Padding(
                  padding: const EdgeInsets.all(14),
                  child: Column(
                    crossAxisAlignment: CrossAxisAlignment.stretch,
                    children: [
                      if (file.mimeType.startsWith('image/') &&
                          file.mimeType != 'image/svg+xml')
                        ClipRRect(
                          borderRadius: BorderRadius.circular(10),
                          child: Image.file(
                            File(file.path),
                            height: 180,
                            fit: BoxFit.contain,
                            errorBuilder: (_, _, _) => const SizedBox(
                              height: 70,
                              child: Center(
                                child: Text(
                                  'Picture unavailable on this device',
                                ),
                              ),
                            ),
                          ),
                        ),
                      const SizedBox(height: 8),
                      Text(
                        file.name,
                        style: const TextStyle(fontWeight: FontWeight.w600),
                      ),
                      Text(
                        '${file.mimeType} · ${file.createdAt.toLocal().toString().split('.').first}',
                        style: TextStyle(
                          fontSize: 12,
                          color: context.luma.textMuted,
                        ),
                      ),
                      Wrap(
                        spacing: 8,
                        children: [
                          TextButton.icon(
                            onPressed: () =>
                                openAssistantArtifact(context, file.path),
                            icon: const Icon(
                              Icons.open_in_new_rounded,
                              size: 16,
                            ),
                            label: const Text('Open'),
                          ),
                          TextButton.icon(
                            onPressed: () => _save(context, file),
                            icon: const Icon(Icons.download_rounded, size: 16),
                            label: const Text('Save a copy'),
                          ),
                          if (file.conversationId != null)
                            TextButton(
                              onPressed: () =>
                                  widget.onOpenChat(file.conversationId!),
                              child: const Text('View chat'),
                            ),
                        ],
                      ),
                    ],
                  ),
                ),
              ),
          ],
        );
      },
    ),
  );

  Future<void> _save(BuildContext context, ChatArtifactRecord file) async {
    try {
      final bytes = await File(file.path).readAsBytes();
      final target = await FilePicker.saveFile(
        dialogTitle: 'Save artifact',
        fileName: file.name,
        bytes: Platform.isAndroid || Platform.isIOS ? bytes : null,
      );
      if (target != null && !Platform.isAndroid && !Platform.isIOS) {
        await File(target).writeAsBytes(bytes, flush: true);
      }
    } catch (error) {
      if (context.mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(content: Text('Could not save the file: $error')),
        );
      }
    }
  }
}
