import '../quiz_bank.dart';

QuizQuestion _q(
  String id,
  String topic,
  String prompt,
  List<String> options,
  int answer, [
  String? why,
]) =>
    QuizQuestion(
      id: id,
      topic: topic,
      prompt: prompt,
      options: options,
      answerIndex: answer,
      explanation: why,
    );

const _woorden = 'Woordenschat';
const _grammatica = 'Grammatica';
const _tijden = 'Werkwoordstijden';

/// Engels, extra oefening voor bovenbouw en brugklas; geen doorstroomtoetsvak.
final List<QuizQuestion> engelsQuestions = [
  // --- Woordenschat ---------------------------------------------------------
  _q('en-001', _woorden, 'Wat betekent "borrow"?',
      ['lenen van iemand', 'uitlenen aan iemand', 'kopen', 'ruilen'], 0,
      '"Lend" is uitlenen, "borrow" is lenen van iemand anders.'),
  _q('en-002', _woorden, 'Wat betekent "although"?',
      ['hoewel', 'daarom', 'omdat', 'behalve'], 0),
  _q('en-003', _woorden, 'Wat is het Engelse woord voor "oefenen"?',
      ['to prevent', 'to practise', 'to prepare', 'to promise'], 1),
  _q('en-004', _woorden, 'Wat betekent "expensive"?',
      ['goedkoop', 'duur', 'zeldzaam', 'nieuw'], 1),
  _q('en-005', _woorden, 'Wat betekent "to remember"?',
      ['vergeten', 'zich herinneren', 'herhalen', 'terugbrengen'], 1),
  _q('en-006', _woorden, 'Wat is het Engelse woord voor "gezond"?',
      ['healthy', 'wealthy', 'heavy', 'hungry'], 0),
  _q('en-007', _woorden, 'Wat betekent "neighbour"?',
      ['buurman of buurvrouw', 'nicht', 'vreemdeling', 'collega'], 0),
  _q('en-008', _woorden, 'Wat betekent "to leave"?',
      ['aankomen', 'vertrekken', 'blijven', 'wachten'], 1),
  _q('en-009', _woorden, 'Wat is het Engelse woord voor "vaak"?',
      ['often', 'ever', 'once', 'never'], 0),
  _q('en-010', _woorden, 'Wat betekent "quiet"?',
      ['stil', 'snel', 'best wel', 'grappig'], 0,
      'Let op: "quite" met een e betekent "best wel".'),
  _q('en-011', _woorden, 'Wat betekent "to buy"?',
      ['verkopen', 'kopen', 'betalen', 'ruilen'], 1),
  _q('en-012', _woorden, 'Wat is het Engelse woord voor "keuken"?',
      ['kitchen', 'chicken', 'cabin', 'closet'], 0),
  _q('en-013', _woorden, 'Wat betekent "dangerous"?',
      ['moeilijk', 'gevaarlijk', 'donker', 'vies'], 1),
  _q('en-014', _woorden, 'Wat betekent "to hurry"?',
      ['zich haasten', 'huilen', 'pijn doen', 'helpen'], 0),
  _q('en-015', _woorden, 'Wat is het Engelse woord voor "gisteren"?',
      ['tomorrow', 'yesterday', 'today', 'tonight'], 1),
  _q('en-016', _woorden, 'Wat betekent "enough"?',
      ['genoeg', 'bijna', 'te veel', 'ook'], 0),
  _q('en-017', _woorden, 'Wat betekent "to grow"?',
      ['groeien', 'gooien', 'grijpen', 'groeten'], 0),
  _q('en-018', _woorden, 'Wat is het Engelse woord voor "advies"?',
      ['advice', 'advertisement', 'adventure', 'address'], 0),
  _q('en-019', _woorden, 'Wat betekent "nearly"?',
      ['bijna', 'dichtbij', 'netjes', 'duidelijk'], 0),
  _q('en-020', _woorden, 'Wat betekent "to lose"?',
      ['losmaken', 'verliezen', 'kiezen', 'sluiten'], 1),

  // --- Grammatica -----------------------------------------------------------
  _q('en-021', _grammatica, 'Vul in: There … a lot of people in the shop.',
      ['is', 'are', 'be', 'am'], 1, '"People" is meervoud, dus "are".'),
  _q('en-022', _grammatica, 'Het boek is van één broer. Vul in: This is … book.',
      ['my brothers', "my brother's", 'my brothers is', "my brothers'"], 1,
      'Bezit bij één broer: apostrof + s.'),
  _q('en-023', _grammatica, 'Wat is het meervoud van "child"?',
      ['childs', 'childes', 'children', 'childrens'], 2),
  _q('en-024', _grammatica, 'Vul in: She is … than her sister.',
      ['tall', 'taller', 'tallest', 'more tall'], 1,
      'Bij een kort bijvoeglijk naamwoord komt -er voor de vergelijking.'),
  _q('en-025', _grammatica, 'Vul in: He is the … boy in the class.',
      ['tall', 'taller', 'tallest', 'most tall'], 2),
  _q('en-026', _grammatica, 'Vul in: I have … apples left.',
      ['much', 'many', 'a lot', 'lot of'], 1,
      '"Many" gebruik je bij telbare woorden, "much" bij niet-telbare.'),
  _q('en-027', _grammatica, 'Vul in: There isn’t … milk in the fridge.',
      ['many', 'much', 'a few', 'lots'], 1),
  _q('en-028', _grammatica, 'Vul in: … you help me, please?',
      ['Can', 'Are', 'Do be', 'Is'], 0),
  _q('en-029', _grammatica, 'Het boek ligt op de tafel. Vul in: The book is … the table.',
      ['in', 'on', 'at', 'by'], 1),
  _q('en-030', _grammatica, 'Vul in: We arrive … Monday.',
      ['in', 'at', 'on', 'to'], 2, 'Bij dagen gebruik je "on".'),
  _q('en-031', _grammatica, 'Vul in: She lives … Amsterdam.',
      ['in', 'on', 'at', 'to'], 0),
  _q('en-032', _grammatica, 'Wat is het meervoud van "mouse"?',
      ['mouses', 'mice', 'mouse', 'mices'], 1),
  _q('en-033', _grammatica, 'Vul in: This pen is … .',
      ['of me', 'mine', 'my', 'me'], 1),
  _q('en-034', _grammatica, 'Vul in: … is your birthday?',
      ['When', 'Where', 'Which', 'Who'], 0),
  _q('en-035', _grammatica, 'Vul in: I saw … in the garden.',
      ['he', 'him', 'his', 'he is'], 1),
  _q('en-036', _grammatica, 'Vul in: She doesn’t like … at all.',
      ['swim', 'swims', 'swimming', 'swam'], 2),
  _q('en-037', _grammatica, 'Welke zin is goed?',
      [
        'He don’t know the answer.',
        'He doesn’t knows the answer.',
        'He doesn’t know the answer.',
        'He not know the answer.'
      ],
      2),
  _q('en-038', _grammatica, 'Vul in: There are … books on the shelf.',
      ['a', 'an', 'some', 'much'], 2),
  _q('en-039', _grammatica, 'Vul in: I would like … apple.',
      ['a', 'an', 'some the', 'any'], 1, 'Voor een klinkerklank komt "an".'),
  _q('en-040', _grammatica, 'Welke zin is goed?',
      [
        'She is more tall than me.',
        'She is taller than me.',
        'She is tallest than me.',
        'She is more taller than me.'
      ],
      1),

  // --- Werkwoordstijden -----------------------------------------------------
  _q('en-041', _tijden, 'Vul in: He … to school every day. (to walk)',
      ['walk', 'walks', 'walking', 'walked'], 1,
      'Present simple bij he/she/it krijgt een -s.'),
  _q('en-042', _tijden, 'Vul in: They … football yesterday. (to play)',
      ['play', 'plays', 'played', 'playing'], 2),
  _q('en-043', _tijden, 'Wat is de verleden tijd van "to go"?',
      ['goed', 'gone', 'went', 'goes'], 2),
  _q('en-044', _tijden, 'Wat is de verleden tijd van "to buy"?',
      ['buyed', 'bought', 'brought', 'buys'], 1),
  _q('en-045', _tijden, 'Wat is de verleden tijd van "to see"?',
      ['seed', 'seen', 'saw', 'sees'], 2),
  _q('en-046', _tijden, 'Vul in: Look! It … . (to rain)',
      ['rains', 'is raining', 'rained', 'rain'], 1,
      '"Look!" wijst op iets dat nu gebeurt: present continuous.'),
  _q('en-047', _tijden, 'Vul in: I … my homework right now. (to do)',
      ['do', 'did', 'am doing', 'does'], 2),
  _q('en-048', _tijden, 'Vul de present continuous in: We … to Spain next summer. (to go)',
      ['go', 'went', 'are going', 'goes'], 2),
  _q('en-049', _tijden, 'Wat is het voltooid deelwoord van "to eat"?',
      ['ate', 'eaten', 'eated', 'eating'], 1),
  _q('en-050', _tijden, 'Vul in: She has … her keys. (to lose)',
      ['lose', 'lost', 'losed', 'losing'], 1),
  _q('en-051', _tijden, 'Wat is de verleden tijd van "to write"?',
      ['writed', 'wrote', 'written', 'writes'], 1),
  _q('en-052', _tijden, 'Vul in: … you finish your homework last night?',
      ['Do', 'Did', 'Does', 'Are'], 1),
  _q('en-053', _tijden, 'Vul in: He … not like fish. (present simple)',
      ['do', 'does', 'did', 'is'], 1),
  _q('en-054', _tijden, 'Wat is de verleden tijd van "to take"?',
      ['taked', 'took', 'taken', 'takes'], 1),
  _q('en-055', _tijden, 'Vul in: I … here since 2019. (to live)',
      ['live', 'lived', 'have lived', 'am living'], 2,
      'Bij "since" gebruik je de present perfect.'),
  _q('en-056', _tijden, 'Wat is de verleden tijd van "to think"?',
      ['thinked', 'thought', 'taught', 'thinks'], 1),
  _q('en-057', _tijden, 'Vul de past continuous in: They … TV when I came in. (to watch)',
      ['watch', 'watched', 'were watching', 'are watching'], 2),
  _q('en-058', _tijden, 'Wat is het voltooid deelwoord van "to drink"?',
      ['drank', 'drunk', 'drinked', 'drinking'], 1),
  _q('en-059', _tijden, 'Vul in: If it rains, we … at home. (to stay)',
      ['stayed', 'will stay', 'have stayed', 'staying'], 1),
  _q('en-060', _tijden, 'Wat is de verleden tijd van "to bring"?',
      ['bringed', 'brang', 'brought', 'bought'], 2),
];
