import '../quiz_bank.dart';

QuizQuestion _q(
  String id,
  String topic,
  String prompt,
  List<String> options,
  int answer, [
  String? why,
]) =>
    QuizQuestion(
      id: id,
      topic: topic,
      prompt: prompt,
      options: options,
      answerIndex: answer,
      explanation: why,
    );

const _spelling = 'Spelling niet-werkwoorden';
const _werkwoorden = 'Werkwoordspelling';
const _leestekens = 'Leestekens';

/// Taalverzorging, groep 8 / doorstroomtoets-niveau.
final List<QuizQuestion> taalverzorgingQuestions = [
  // --- Spelling niet-werkwoorden -------------------------------------------
  _q('tv-001', _spelling, 'Welk woord is goed geschreven?',
      ['kado', 'cadeau', 'kadeau', 'cadau'], 1,
      'Een leenwoord uit het Frans houdt zijn Franse schrijfwijze.'),
  _q('tv-002', _spelling, 'Welk woord is goed geschreven?',
      ['pannekoek', 'pannenkoek', 'panekoek', 'pannenkoeck'], 1,
      'Pan heeft alleen het meervoud pannen, dus een tussen-n.'),
  _q('tv-003', _spelling, 'Welk woord is goed geschreven?',
      ['zeeeend', 'zeeëend', 'zee-eend', 'zee eend'], 2,
      'Bij een samenstelling met klinkerbotsing komt een koppelteken.'),
  _q('tv-004', _spelling, 'Welk woord is goed geschreven?',
      ['ideeen', 'ideeën', 'idee-en', 'ideën'], 1,
      'Binnen één woord voorkom je klinkerbotsing met een trema.'),
  _q('tv-005', _spelling, 'Welk woord is goed geschreven?',
      ['bessesap', 'bessensap', 'bessen-sap', 'bessansap'], 1,
      'Bes heeft alleen het meervoud bessen, dus een tussen-n.'),
  _q('tv-006', _spelling, 'Welk woord is goed geschreven?',
      ['ruggegraat', 'ruggengraat', 'rugge-graat', 'rugsgraat'], 1,
      'Sinds 1995 schrijf je ruggengraat met een tussen-n.'),
  _q('tv-007', _spelling, 'Welk woord is goed geschreven?',
      ['zonnenbloem', 'zonnebloem', 'zonne-bloem', 'zonnbloem'], 1,
      'De zon is er maar één, en dan blijft de tussen-n weg.'),
  _q('tv-008', _spelling, 'Welk woord is goed geschreven?',
      ['restaurant', 'resturant', 'restourant', 'restaurent'], 0),
  _q('tv-009', _spelling, 'Welk woord is goed geschreven?',
      ['naapen', 'na-apen', 'naäpen', 'na apen'], 1,
      'Twee dezelfde klinkers tegen elkaar in een samenstelling: koppelteken.'),
  _q('tv-010', _spelling, 'Wat is het meervoud van "boom"?',
      ['bommen', 'bomen', 'boomen', 'boomens'], 1,
      'De lange oo wordt in een open lettergreep één o.'),
  _q('tv-011', _spelling, 'Welk woord is goed geschreven?',
      ['sjocolade', 'chocolade', 'chokolade', 'chocalade'], 1),
  _q('tv-012', _spelling, 'Welke zin is goed geschreven?',
      [
        'Wij gaan in Juli naar frankrijk.',
        'Wij gaan in juli naar Frankrijk.',
        'wij gaan in juli naar Frankrijk.',
        'Wij gaan in Juli naar Frankrijk.'
      ],
      1,
      'Maanden krijgen geen hoofdletter, landen wel.'),
  _q('tv-013', _spelling, 'Welke zin is goed geschreven?',
      [
        'Hij spreekt nederlands en duits.',
        'Hij spreekt Nederlands en Duits.',
        'Hij spreekt Nederlands en duits.',
        'hij spreekt Nederlands en Duits.'
      ],
      1,
      'Namen van talen krijgen een hoofdletter.'),
  _q('tv-014', _spelling, 'Wat is het meervoud van "foto"?',
      ["fotos", "foto's", "fotoos", "fotoen"], 1,
      'Na een losse klinker komt een apostrof voor de meervouds-s.'),
  _q('tv-015', _spelling, 'Wat is het meervoud van "baby"?',
      ["babys", "baby's", "babies", "babyen"], 1,
      'Ook hier houdt de apostrof de klank van de y intact.'),
  _q('tv-016', _spelling, 'Welk woord is goed geschreven?',
      ['ontbeit', 'ontbijt', 'ontbeidt', 'ontbeijt'], 1),
  _q('tv-017', _spelling, 'Wat is het verkleinwoord van "ring"?',
      ['ringje', 'ringetje', 'rinkje', 'ringtje'], 1,
      'Na een korte klinker met -ng komt -etje.'),
  _q('tv-018', _spelling, 'Wat is het verkleinwoord van "koning"?',
      ['koningje', 'koninkje', 'koningtje', 'koninkietje'], 1,
      'Bij woorden op -ing zonder klemtoon achteraan wordt het -kje.'),
  _q('tv-019', _spelling, 'Welk woord is FOUT geschreven?',
      ['fietsenrek', 'pannenkoek', 'ruggegraat', 'zonnebloem'], 2,
      'Het moet ruggengraat zijn, met tussen-n.'),
  _q('tv-020', _spelling, 'Welk woord is goed geschreven?',
      ['lineaal', 'liniaal', 'linjaal', 'lininaal'], 1),
  _q('tv-021', _spelling, 'Welk woord is goed geschreven?',
      ['nieuwschierig', 'nieuwsgierig', 'nieuwgierig', 'nieuwsgierrig'], 1),
  _q('tv-022', _spelling, 'Welk woord is goed geschreven?',
      ['ambulanse', 'ambulance', 'ambelance', 'ambulantse'], 1),
  _q('tv-023', _spelling, 'Welk woord is goed geschreven?',
      ['reunie', 'reünie', 're-unie', 'reuunie'], 1,
      'Het trema laat zien dat de u apart uitgesproken wordt.'),
  _q('tv-024', _spelling, 'Welk woord is goed geschreven?',
      ['coordinaten', 'coördinaten', 'co-ordinaten', 'koördinaten'], 1),
  _q('tv-025', _spelling, 'Welk woord krijgt een koppelteken?',
      ['autoongeluk', 'auto-ongeluk', 'autoöngeluk', 'auto ongeluk'], 1,
      'De o van auto botst met de o van ongeluk.'),
  _q('tv-026', _spelling, 'Welk woord is goed geschreven?',
      ['gymnasiek', 'gymnastiek', 'gimnastiek', 'gymnastik'], 1),
  _q('tv-027', _spelling, 'Wat is het meervoud van "bal" (om mee te spelen)?',
      ['balen', 'ballen', 'balls', 'ballens'], 1,
      'De korte a blijft kort, dus komt er een dubbele l.'),
  _q('tv-028', _spelling, 'Welk woord is goed geschreven?',
      ['ekonomie', 'economie', 'eçonomie', 'ecconomie'], 1),

  // --- Werkwoordspelling ----------------------------------------------------
  _q('tv-029', _werkwoorden,
      'Vul in: Gisteren … mijn buren naar Utrecht. (verhuizen)',
      ['verhuisde', 'verhuisden', 'verhuizden', 'verhuizen'], 1,
      'Het onderwerp "mijn buren" is meervoud, dus verhuisden.'),
  _q('tv-030', _werkwoorden, 'Vul in: Hij … morgen twaalf jaar. (worden)',
      ['word', 'wordt', 'wort', 'worden'], 1,
      'Bij hij/zij/het komt er een t bij de stam.'),
  _q('tv-031', _werkwoorden, 'Vul in: Wanneer … jij jarig? (worden)',
      ['word', 'wordt', 'wordtt', 'worden'], 0,
      'Staat jij ACHTER het werkwoord, dan valt de t weg.'),
  _q('tv-032', _werkwoorden, 'Vul in: Ik … de brief gisteren. (versturen)',
      ['verstuurde', 'verstuurdde', 'verstuurte', 'verstuurd'], 0,
      'De stam eindigt op r, dus verleden tijd met -de.'),
  _q('tv-033', _werkwoorden, 'Vul in: Hij heeft de vraag … (beantwoorden)',
      ['beantwoord', 'beantwoordt', 'beantwoordde', 'beantwoorden'], 0,
      'Een voltooid deelwoord krijgt nooit een extra t.'),
  _q('tv-034', _werkwoorden, 'Vul in: Zij hebben lang … (praten)',
      ['gepraat', 'gepraadt', 'gepraten', 'praatten'], 0,
      "'t kofschip: de t van praten zit erin, dus -t."),
  _q('tv-035', _werkwoorden, 'Vul in: De hond … hard. (blaffen, verleden tijd)',
      ['blafte', 'blafde', 'blaffte', 'blaftte'], 0,
      "De f van 't kofschip geeft -te."),
  _q('tv-036', _werkwoorden,
      'Vul in: Wij … naar huis. (fietsen, verleden tijd)',
      ['fietste', 'fietsten', 'fietsden', 'fietseden'], 1,
      'Meervoud in de verleden tijd: stam + ten.'),
  _q('tv-037', _werkwoorden,
      'Vul in: Zij … het raam. (openen, verleden tijd, één persoon)',
      ['opende', 'openden', 'opendde', 'openende'], 0,
      "De n hoort niet bij 't kofschip, dus -de."),
  _q('tv-038', _werkwoorden, 'Vul in: Hij heeft het geld … (verdienen)',
      ['verdient', 'verdiend', 'verdiende', 'verdienden'], 1,
      'Het voltooid deelwoord van verdienen is verdiend, met een d.'),
  _q('tv-039', _werkwoorden, 'Vul in: Het … geld is terecht. (beloven)',
      ['beloofd', 'beloofde', 'belooft', 'beloven'], 1,
      'Een deelwoord vóór een zelfstandig naamwoord krijgt een -e.'),
  _q('tv-040', _werkwoorden,
      'Vul in: Ik … je morgen. (bellen, tegenwoordige tijd)',
      ['bel', 'belt', 'beld', 'belde'], 0,
      'Bij ik gebruik je de kale stam.'),
  _q('tv-041', _werkwoorden, 'Vul in: Jij … de deur. (sluiten)',
      ['sluit', 'sluitt', 'sluid', 'sluiten'], 0,
      'Jij vóór het werkwoord: stam + t, maar de stam eindigt al op t.'),
  _q('tv-042', _werkwoorden,
      'Vul in: Hij … gisteren de wedstrijd. (winnen, verleden tijd)',
      ['winde', 'won', 'wonde', 'winnede'], 1,
      'Winnen is een sterk werkwoord: winnen – won – gewonnen.'),
  _q('tv-043', _werkwoorden, 'Vul in: Zij hebben de wedstrijd … (winnen)',
      ['gewonnen', 'gewonen', 'gewint', 'winnen'], 0),
  _q('tv-044', _werkwoorden, 'Vul in: Wat … jij daarvan? (vinden)',
      ['vind', 'vindt', 'vint', 'vinden'], 0,
      'Jij staat achter het werkwoord, dus zonder t.'),
  _q('tv-045', _werkwoorden, 'Vul in: Hij … dat een goed idee. (vinden)',
      ['vind', 'vindt', 'vint', 'vinden'], 1,
      'Stam vind + t, ook al hoor je die t niet.'),
  _q('tv-046', _werkwoorden,
      'Vul in: Wij … elke dag om het hardst. (rennen, verleden tijd)',
      ['rende', 'renden', 'rennden', 'renneden'], 1),
  _q('tv-047', _werkwoorden, 'Vul in: De zon … vandaag volop. (schijnen)',
      ['schijn', 'schijnt', 'schijnd', 'schijnen'], 1),
  _q('tv-048', _werkwoorden,
      'Vul in: Hij is met de trein naar Parijs … (reizen)',
      ['gereist', 'gereisd', 'gereizd', 'reisde'], 1,
      "De z hoort niet bij 't kofschip, dus het deelwoord krijgt een d."),
  _q('tv-049', _werkwoorden, 'Vul in: Ik heb dat boek al … (lezen)',
      ['gelezen', 'geleesd', 'gelezt', 'lezen'], 0),
  _q('tv-050', _werkwoorden,
      'Vul in: Het feest … morgen om acht uur. (beginnen)',
      ['begin', 'begint', 'begind', 'beginnen'], 1),
  _q('tv-051', _werkwoorden,
      'Vul in: Zij … vroeger in Almere. (wonen, verleden tijd, meervoud)',
      ['woonde', 'woonden', 'wonden', 'woonten'], 1),
  _q('tv-052', _werkwoorden, 'Vul in: Hij heeft de hele dag hard … (werken)',
      ['gewerkt', 'gewerkd', 'werkte', 'gewerken'], 0,
      "De k van 't kofschip geeft een t."),
  _q('tv-053', _werkwoorden, 'Vul in: Waarom … hij zo boos? (worden)',
      ['word', 'wordt', 'wort', 'worden'], 1,
      'Hij krijgt altijd stam + t, ook in een vraag.'),
  _q('tv-054', _werkwoorden, 'Vul in: De … auto staat voor de deur. (verkopen)',
      ['verkoopte', 'verkochte', 'verkochtte', 'verkocht'], 1,
      'Het deelwoord verkocht krijgt als bijvoeglijk naamwoord een -e.'),
  _q('tv-055', _werkwoorden, 'Vul in: Ik … altijd mijn best. (doen)',
      ['doe', 'doet', 'doed', 'doen'], 0),
  _q('tv-056', _werkwoorden,
      'Vul in: Hij … zijn huiswerk niet. (maken, verleden tijd)',
      ['maakte', 'maakde', 'maaktte', 'makte'], 0),

  // --- Leestekens -----------------------------------------------------------
  _q('tv-057', _leestekens, 'Welke zin is goed geschreven?',
      [
        'Ik kocht brood kaas, en melk.',
        'Ik kocht brood, kaas en melk.',
        'Ik kocht, brood, kaas en melk.',
        'Ik kocht brood, kaas, en melk.'
      ],
      1,
      'In een opsomming staat geen komma voor het laatste "en".'),
  _q('tv-058', _leestekens, 'Welke zin is goed geschreven?',
      [
        'Kom je nog? vroeg Sam.',
        '"Kom je nog?" vroeg Sam.',
        '"Kom je nog"? vroeg Sam.',
        '"Kom je nog?", vroeg Sam.'
      ],
      1,
      'Het vraagteken hoort binnen de aanhalingstekens.'),
  _q('tv-059', _leestekens, 'Welke zin is goed geschreven?',
      [
        'Kun je me helpen Lisa?',
        'Kun je me helpen, Lisa?',
        'Kun je me, helpen Lisa?',
        'Kun je me helpen Lisa.'
      ],
      1,
      'Voor een aanspreking komt een komma.'),
  _q('tv-060', _leestekens, 'Welke zin is goed geschreven?',
      [
        'Toen het ging regenen gingen we naar binnen.',
        'Toen het ging regenen, gingen we naar binnen.',
        'Toen, het ging regenen gingen we naar binnen.',
        'Toen het ging regenen; gingen we naar binnen.'
      ],
      1,
      'Na een bijzin vooraan de zin komt een komma.'),
  _q('tv-061', _leestekens,
      'Welk leesteken hoort op de puntjes? "Je hebt drie dingen nodig … een pen, papier en een liniaal."',
      ['een komma', 'een dubbele punt', 'een punt', 'een puntkomma'], 1,
      'Een dubbele punt kondigt een opsomming aan.'),
  _q('tv-062', _leestekens, 'Welke zin is goed geschreven?',
      [
        "Anna's fiets staat buiten.",
        'Annas fiets staat buiten.',
        "Anna`s fiets staat buiten.",
        'Anna s fiets staat buiten.'
      ],
      0,
      'Bij een naam op een klinker komt een apostrof voor de bezits-s.'),
  _q('tv-063', _leestekens, 'Welke zin is goed geschreven?',
      [
        'Wat een geweldige wedstrijd.',
        'Wat een geweldige wedstrijd!',
        'Wat een geweldige wedstrijd?',
        'Wat een geweldige wedstrijd,'
      ],
      1,
      'Een uitroep krijgt een uitroepteken.'),
  _q('tv-064', _leestekens, 'Welke zin is goed geschreven?',
      [
        'Hij vroeg of ik mee ging?',
        'Hij vroeg of ik mee ging.',
        'Hij vroeg: of ik mee ging?',
        'Hij vroeg, of ik mee ging?'
      ],
      1,
      'Dit is een mededeling over een vraag, geen vraag zelf.'),
  _q('tv-065', _leestekens,
      'Waar hoort de komma in deze zin? "Omdat het regende bleven we thuis."',
      [
        'na "Omdat"',
        'na "regende"',
        'na "bleven"',
        'er hoort geen komma in'
      ],
      1,
      'De bijzin eindigt bij regende, daarna komt de komma.'),
  _q('tv-066', _leestekens, 'Welke zin is goed geschreven?',
      [
        '"Ik kom eraan," riep Tom.',
        '"Ik kom eraan." riep Tom.',
        '"Ik kom eraan" riep Tom.',
        'Ik kom eraan, riep Tom".'
      ],
      0,
      'De komma vervangt de punt en staat binnen de aanhalingstekens.'),
  _q('tv-067', _leestekens, 'Welke zin is goed geschreven?',
      [
        'Mijn broer die in Utrecht woont, komt vanavond.',
        'Mijn broer, die in Utrecht woont, komt vanavond.',
        'Mijn broer, die in Utrecht woont komt vanavond.',
        'Mijn broer die in Utrecht woont komt, vanavond.'
      ],
      1,
      'Een tussenzin staat tussen twee komma’s.'),
  _q('tv-068', _leestekens, 'Welk leesteken zet je aan het eind van een vraag?',
      ['een punt', 'een vraagteken', 'een uitroepteken', 'een komma'], 1),
  _q('tv-069', _leestekens, 'Welke zin is goed geschreven?',
      [
        'We namen mee: brood, fruit en drinken.',
        'We namen mee, brood, fruit en drinken.',
        'We namen mee; brood, fruit en drinken.',
        'We namen mee. brood, fruit en drinken.'
      ],
      0),
  _q('tv-070', _leestekens, 'Welke zin is goed geschreven?',
      [
        'Nee dank je ik hoef niets.',
        'Nee, dank je, ik hoef niets.',
        'Nee dank je, ik hoef niets',
        'Nee; dank je; ik hoef niets.'
      ],
      1),
  _q('tv-071', _leestekens, 'Wat doe je met een boektitel midden in een zin?',
      [
        'Je zet er aanhalingstekens omheen of je cursiveert hem',
        'Je zet er altijd een uitroepteken achter',
        'Je schrijft hem volledig in hoofdletters',
        'Je zet er haakjes omheen'
      ],
      0),
  _q('tv-072', _leestekens, 'Welke zin is goed geschreven?',
      [
        'Hij zei dat hij ziek was en niet kwam.',
        'Hij zei, dat hij ziek was en niet kwam.',
        'Hij zei dat hij ziek was, en niet kwam.',
        'Hij zei: dat hij ziek was en niet kwam.'
      ],
      0,
      'Voor "dat" komt in het Nederlands geen komma.'),
  _q('tv-073', _leestekens, 'Welke zin is goed geschreven?',
      [
        'Sara, Bram en Iris gingen mee.',
        'Sara Bram en Iris gingen mee.',
        'Sara, Bram, en Iris gingen mee.',
        'Sara; Bram en Iris gingen mee.'
      ],
      0),
  _q('tv-074', _leestekens,
      'Welk leesteken zet je tussen twee zinnen die sterk bij elkaar horen, in plaats van een punt?',
      ['een komma', 'een puntkomma', 'een dubbele punt', 'een streepje'], 1),
  _q('tv-075', _leestekens, 'Welke zin is goed geschreven?',
      [
        'Wanneer begint de film!',
        'Wanneer begint de film?',
        'Wanneer begint de film.',
        'Wanneer begint de film,'
      ],
      1),
  _q('tv-076', _leestekens, 'Welke zin is goed geschreven?',
      [
        'Ik wil, appels peren en bananen.',
        'Ik wil appels, peren en bananen.',
        'Ik wil appels peren, en bananen.',
        'Ik wil: appels peren en bananen.'
      ],
      1),
  _q('tv-077', _leestekens, 'Welke zin is goed geschreven?',
      [
        'Als je klaar bent mag je gaan.',
        'Als je klaar bent, mag je gaan.',
        'Als, je klaar bent mag je gaan.',
        'Als je klaar bent mag, je gaan.'
      ],
      1),
  _q('tv-078', _leestekens, 'Welke zin is goed geschreven?',
      [
        'Pas op! Er komt een fietser aan.',
        'Pas op. Er komt een fietser aan!',
        'Pas op, er komt een fietser aan?',
        'Pas op? Er komt een fietser aan.'
      ],
      0),
  _q('tv-079', _leestekens, 'Welke zin is goed geschreven?',
      [
        'Amsterdam, de hoofdstad van Nederland ligt aan het IJ.',
        'Amsterdam, de hoofdstad van Nederland, ligt aan het IJ.',
        'Amsterdam de hoofdstad van Nederland, ligt aan het IJ.',
        'Amsterdam de hoofdstad van Nederland ligt aan het IJ.'
      ],
      1,
      'De uitleg tussen de komma’s is een bijstelling.'),
  _q('tv-080', _leestekens, 'Welke zin is goed geschreven?',
      [
        '"Waar ga je heen?" vroeg mijn moeder.',
        '"Waar ga je heen"? vroeg mijn moeder.',
        'Waar ga je heen? "vroeg mijn moeder."',
        '"Waar ga je heen?, vroeg mijn moeder."'
      ],
      0),
];
