/// The AI Detector's brain: a set of statistical writing-style checks that
/// estimate how machine-generated a piece of text reads.
///
/// There is deliberately no model here — no network, no embeddings, no
/// inference. Every signal is arithmetic on the words themselves, in the same
/// spirit as stylometry: LLM output tends to be *uniform* (steady sentence
/// lengths, tidy paragraphs, formal register) and leans on a recognisable
/// vocabulary. Humans are burstier and sloppier.
///
/// The one exception is the Claude watermark scan, which does not measure
/// style at all: it looks for the invisible characters and self-references a
/// generated text carries inside itself. Those can name an author outright,
/// which no statistic ever can, so a hit there promotes the verdict from
/// "AI-generated" to "Generated by Claude".
///
/// Each check produces an [AiTrigger] with a 0..1 strength, and the checks
/// come in two kinds that are scored very differently.
///
/// *Two-sided* checks measure rhythm — sentence-length spread, paragraph
/// spread, contractions, register — and a text can genuinely read human on
/// them, so they average both ways. Because formal human prose looks machine
/// uniform too, rhythm alone tops out below the highest band.
///
/// *One-way* checks (see [AiTrigger.oneWay]) look for things only generated
/// text tends to carry: a stock phrase, chat formatting, a corrective
/// contrast, a watermark. Finding one is evidence; finding none is not
/// evidence of a human hand, since most generated text carries no stock
/// phrase at all. These therefore only ever add to the score. Treating them
/// as two-sided was what let a fully generated essay score "mixed" — it
/// collected full-weight "human" votes simply for containing no em dashes
/// and no passive voice.
///
/// The two are combined the way independent suspicions combine, so either
/// can carry a verdict alone. Checks whose sample is too small to mean
/// anything stay out entirely rather than defaulting to "human". Every check
/// also reports the exact stretches of text it matched as [AiHighlight]s, so
/// the report can paint its evidence onto the source.
library;

import 'dart:math' as math;

/// One measured signal in the report.
class AiTrigger {
  const AiTrigger({
    required this.id,
    required this.title,
    required this.detail,
    required this.strength,
    this.evidence = const [],
    this.oneWay = false,
  });

  /// Stable identifier, e.g. `burstiness`.
  final String id;

  /// Short headline shown in the report list.
  final String title;

  /// One or two sentences explaining what was measured and why it matters.
  final String detail;

  /// 0..1 — how strongly this check fired. Below ~0.15 it counts as quiet.
  final double strength;

  /// Concrete proof pulled from the text: matched phrases, measured ranges,
  /// rates. Shown as chips under the trigger so the verdict can be checked.
  final List<String> evidence;

  /// True when this check can only ever *incriminate*.
  ///
  /// Finding a stock phrase, an em-dash storm or a watermark is evidence the
  /// text was generated. Finding none of them is not evidence it was not —
  /// plenty of generated text carries no stock phrase at all. A one-way
  /// check therefore adds to the score when it fires and abstains when it
  /// does not, instead of voting the score down the way a genuinely
  /// two-sided measurement can.
  final bool oneWay;

  bool get fired => strength >= 0.15;
}

/// Where a highlight came from. Each kind carries its own [severity] so the
/// renderer can paint a conclusive signature differently from a mild
/// stylistic tell, and so overlapping flags resolve to the stronger one.
enum AiHighlightKind {
  emDash('Em dash'),
  passive('Passive voice'),
  opener('Transition opener'),
  phrase('AI-favourite phrase'),
  assistant('Assistant boilerplate'),
  claudeName('Claude signature'),
  watermark('Claude watermark');

  const AiHighlightKind(this.label);

  /// Short name used in the highlight legend.
  final String label;

  /// 0 = mild stylistic tell, 1 = strong, 2 = conclusive.
  int get severity => switch (this) {
        AiHighlightKind.emDash ||
        AiHighlightKind.passive ||
        AiHighlightKind.opener =>
          0,
        AiHighlightKind.phrase || AiHighlightKind.assistant => 1,
        AiHighlightKind.claudeName || AiHighlightKind.watermark => 2,
      };
}

/// One stretch of the analysed text that a check flagged, so the report can
/// paint it in place instead of only describing it in a list.
class AiHighlight {
  const AiHighlight({
    required this.start,
    required this.end,
    required this.kind,
    required this.note,
  });

  /// UTF-16 offsets into the analysed text; [end] is exclusive.
  final int start;
  final int end;
  final AiHighlightKind kind;

  /// Why this stretch was flagged, shown in the legend and on hover.
  final String note;
}

/// Who the text is attributed to. Attribution only ever comes from a
/// signature the text carries itself — a hidden watermark character or a
/// self-reference. Style statistics alone can never name a model, so they
/// leave this at [AiAuthor.unknown].
enum AiAuthor { unknown, claude }

/// Everything the report page needs for one analysed text.
class AiDetectorReport {
  const AiDetectorReport({
    required this.score,
    required this.wordCount,
    required this.sentenceCount,
    required this.avgSentenceWords,
    required this.triggers,
    this.highlights = const [],
    this.author = AiAuthor.unknown,
  });

  /// 0..100 — higher reads more machine-like.
  final double score;
  final int wordCount;
  final int sentenceCount;
  final double avgSentenceWords;
  final List<AiTrigger> triggers;

  /// Every flagged stretch of the original text, merged and sorted by
  /// position, ready to paint straight onto the source.
  final List<AiHighlight> highlights;

  /// Set when the text signs itself — see [claudeSigned].
  final AiAuthor author;

  /// Short texts make every statistic meaningless; the UI shows a caution
  /// banner when this is false.
  bool get reliable => wordCount >= 60 && sentenceCount >= 4;

  /// True when the Claude watermark scan found something conclusive. That
  /// turns the verdict from a hedged "AI-generated" into a named
  /// attribution, because a signature identifies its writer where style
  /// statistics only ever describe one.
  bool get claudeSigned => author == AiAuthor.claude;

  /// Flagged stretches grouped by kind, for the highlight legend.
  Map<AiHighlightKind, int> get highlightCounts {
    final counts = <AiHighlightKind, int>{};
    for (final h in highlights) {
      counts[h.kind] = (counts[h.kind] ?? 0) + 1;
    }
    return counts;
  }

  String get verdict {
    if (claudeSigned) return 'Generated by Claude';
    if (score < 18) return 'Very likely human-written';
    if (score < 38) return 'Likely human-written';
    if (score < 58) return 'Mixed signals';
    if (score < 78) return 'Likely AI-generated';
    return 'Very likely AI-generated';
  }
}

class AiDetectorEngine {
  AiDetectorEngine._();

  /// The highest score rhythm alone can reach. Uniform sentences and tidy
  /// paragraphs are a strong suspicion, never a conviction — formal human
  /// writing looks the same — so the top of the scale is reserved for texts
  /// that also carry hard evidence.
  static const _styleCeiling = 72.0;

  /// Weighted one-way evidence needed to max the remaining scale. Set so
  /// that roughly two firing signals saturate it.
  static const _boostSaturation = 45.0;

  /// Phrases near-exclusive to model prose. One of these in an ordinary
  /// paragraph already means something. Matched case-insensitively on word
  /// boundaries.
  static const _strongPhrases = [
    'delve into', 'delves into', 'delving into',
    'a testament to', 'stands as a testament', 'serves as a testament',
    'tapestry', 'rich tapestry',
    "in today's fast-paced world", "in today's digital age",
    'ever-evolving landscape', 'ever-evolving', 'ever-changing landscape',
    'in the realm of',
    "it's important to note", 'it is important to note',
    "it's worth noting", 'it is worth noting',
    'it is essential to', 'it is crucial to',
    'navigate the complexities', 'navigating the complexities',
    'plays a crucial role', 'play a crucial role',
    'plays a vital role', 'play a vital role',
    'plays a significant role', 'pivotal role',
    'myriad of', 'plethora of',
    'multifaceted',
    'holistic approach',
    'harness the power', 'harnessing the power',
    'unlock the potential', 'unlocking the potential',
    'game-changer', 'game changer',
    'paradigm shift',
    'beacon of',
    'sheds light on', 'shedding light on',
    'paves the way', 'paving the way',
    'intricacies',
    'interplay between',
    'double-edged sword',
    'cannot be overstated',
    'treasure trove',
    'embark on a journey',
    'underscores the importance', 'underscoring the importance',
    'in conclusion', 'in summary', 'to summarize', 'to summarise',
  ];

  /// Vocabulary models lean on heavily but that humans writing in a corporate
  /// or academic register use too. Counted at a discount, so a couple of them
  /// mean little while a dense cluster still registers.
  static const _softPhrases = [
    'seamless', 'seamlessly',
    'unleash', 'unleashing',
    'deep dive', 'dive into',
    'embark on',
    'underscores', 'underscoring',
    'meticulous', 'meticulously',
    'not only', 'but also',
    'leverage', 'leveraging',
    'streamline', 'streamlining',
    'foster', 'fostering',
    'robust',
    'utilize', 'utilizing',
    'facilitate', 'facilitating',
    'nuanced',
    'comprehensive',
    'the realm of', 'landscape of',
    'when it comes to',
    'the world of',
    'moving forward',
    'key takeaway', 'key takeaways',
    'at the end of the day',
  ];

  static final _phraseRes = <String, RegExp>{
    for (final p in [..._strongPhrases, ..._softPhrases])
      p: RegExp('\\b${RegExp.escape(p)}\\b', caseSensitive: false),
  };

  static final _strongPhraseSet = _strongPhrases.toSet();

  /// The rhetorical shapes current models reach for when they want to sound
  /// insightful: the corrective contrast, the staged reveal, the pivot to
  /// "what's really going on". Humans write these too, just nowhere near as
  /// reliably, so they are counted as one more incriminating signal rather
  /// than treated as proof.
  static final _contrastRes = <String, RegExp>{
    '"not just X, but Y"': RegExp(
      r"\bnot (?:just|only|merely|simply)\b[^.!?\n]{0,90}?"
      r"\b(?:but|it(?:'s|’s| is))\b",
      caseSensitive: false,
    ),
    '"it’s not X. It’s Y."': RegExp(
      r"\b(?:it|this|that)(?:'s|’s| is)\s+not\s+"
      r'(?:about|that|a|the)\b[^.!?\n]{0,70}[.!?]\s+'
      r"(?:it|this|that)(?:'s|’s| is)\b",
      caseSensitive: false,
    ),
    '"isn’t just" construction': RegExp(
      r"\b(?:isn|aren|wasn|weren|doesn|don)(?:'|’)t\s+"
      r'(?:just|only|merely|simply|about)\b',
      caseSensitive: false,
    ),
    'staged reveal': RegExp(
      r'\bthe (?:real|actual|hard|interesting|important|key) '
      r'(?:question|problem|answer|issue|part|insight|point|reason)\b',
      caseSensitive: false,
    ),
    '"that’s the point" close': RegExp(
      r"\bthat(?:'s|’s| is) (?:the|exactly the|precisely the) "
      r'(?:point|whole point|key|catch|trick|difference)\b',
      caseSensitive: false,
    ),
    '"here’s the thing" pivot': RegExp(
      r"\bhere(?:'s|’s| is) (?:the thing|the catch|where|why|what)\b",
      caseSensitive: false,
    ),
  };

  /// Scaffolding that survives a copy-paste out of a chat window: markdown
  /// headings, bullet runs, numbered steps, and the bolded "Label: text"
  /// list item that chat models format almost every answer with.
  static final _headingRe = RegExp(r'^\s{0,3}#{1,6}\s+\S', multiLine: true);
  static final _bulletRe =
      RegExp(r'^\s{0,6}(?:[-*•‣◦]|\d{1,2}[.)])\s+\S',
          multiLine: true);
  static final _boldLeadRe = RegExp(
    r'^\s{0,6}(?:[-*•]\s+)?\*\*[^*\n]{2,60}\*\*\s*[:—-]',
    multiLine: true,
  );
  static final _labelLeadRe = RegExp(
    r'^\s{0,6}(?:[-*•]\s+)?[A-Z][A-Za-z0-9 /&’\x27-]{2,40}:\s+\S',
    multiLine: true,
  );

  /// Pronouns that put a person on the page. Expository human writing uses
  /// fewer of them, which is why this check carries a modest weight.
  static const _personalPronouns = {
    'i', 'me', 'my', 'mine', 'myself',
    'we', 'us', 'our', 'ours',
    'you', 'your', 'yours',
  };

  /// Casual register markers. Models write these far more rarely than people
  /// do outside of a deliberately breezy prompt.
  static const _informalWords = {
    'honestly', 'anyway', 'anyhow', 'kinda', 'sorta', 'gonna', 'wanna',
    'stuff', 'thing', 'things', 'weird', 'okay', 'yeah', 'yep', 'nope',
    'huh', 'oops', 'messy', 'mess', 'guess', 'maybe', 'probably', 'dunno',
    'basically', 'actually', 'really', 'pretty', 'bit', 'lot', 'whatever',
    'anyways', 'ugh', 'wow', 'damn', 'sucks', 'stupid', 'silly', 'nice',
  };

  /// Sentence openers that suggest formulaic paragraph-by-paragraph flow.
  static const _connectives = [
    'however', 'moreover', 'furthermore', 'additionally', 'consequently',
    'nevertheless', 'ultimately', 'overall', 'indeed', 'thus', 'therefore',
    'hence', 'meanwhile', 'subsequently',
  ];

  /// First words too common to count as stylistic repetition when several
  /// sentences share them.
  static const _openerStopwords = {
    'the', 'a', 'an', 'i', 'it', 'this', 'that', 'these', 'those', 'there',
    'here', 'if', 'in', 'on', 'at', 'to', 'for', 'of', 'with', 'as', 'but',
    'and', 'or', 'so', 'he', 'she', 'we', 'they', 'you', 'my', 'his', 'her',
    'their', 'our', 'its', 'when', 'while', 'what', 'why', 'how', 'not',
  };

  /// Code points that occupy no visual space at all. Nothing a person types
  /// produces a run of these; they are the carrier any text watermark has to
  /// use, because the payload must survive copy-paste while staying invisible.
  static const _invisible = <int, String>{
    0x00AD: 'soft hyphen',
    0x034F: 'combining grapheme joiner',
    0x180E: 'Mongolian vowel separator',
    0x200B: 'zero-width space',
    0x200C: 'zero-width non-joiner',
    0x200D: 'zero-width joiner',
    0x2060: 'word joiner',
    0x2061: 'function application',
    0x2062: 'invisible times',
    0x2063: 'invisible separator',
    0x2064: 'invisible plus',
    0xFEFF: 'zero-width no-break space',
  };

  /// Signatures that name Claude outright. Deliberately narrow: a bare
  /// "Claude" is a person's name far more often than a model's, so every
  /// pattern needs the surrounding product context before it counts.
  static final _claudeRes = <String, RegExp>{
    'claude.ai referenced':
        RegExp(r'\bclaude\.ai\b', caseSensitive: false),
    'Anthropic named': RegExp(r'\banthropic\b', caseSensitive: false),
    'Claude model id': RegExp(
      r'\bclaude[-\s](?:instant|opus|sonnet|haiku|fable|'
      r'[1-9](?:\.[0-9])?)\b',
      caseSensitive: false,
    ),
    'Claude self-reference': RegExp(
      r"\b(?:i(?:'m|’m| am)|this is|you(?:'re|’re| are) "
      r'(?:talking to|chatting with|speaking with))\s+claude\b',
      caseSensitive: false,
    ),
  };

  /// Stock assistant phrasing. It proves the text came out of a chat model
  /// but not *which* one, so it raises the score without naming an author.
  static final _assistantRes = <String, RegExp>{
    '"As an AI" disclaimer': RegExp(
      r'\bas an ai(?:\s+(?:language\s+model|assistant|model))?\b|'
      r"\bi(?:'m|’m| am) an ai\b",
      caseSensitive: false,
    ),
    'capability disclaimer': RegExp(
      r'\bi (?:do not|don’t|don\x27t) have (?:personal|access to '
      r'real-time|the ability)\b|\bi cannot browse\b|'
      r'\bmy (?:knowledge|training) (?:cutoff|data)\b',
      caseSensitive: false,
    ),
    'chat sign-off': RegExp(
      r'\bi hope (?:this|that) helps\b|'
      r'\bis there anything else (?:i can help|you)\b|'
      r'\blet me know if you (?:have|need|’d|\x27d)\b',
      caseSensitive: false,
    ),
  };

  static final _wordRe =
      RegExp(r"[A-Za-z0-9\u00C0-\u024F]+(?:['\u2019][A-Za-z]+)?");
  static final _sentenceSplitRe = RegExp(r'[.!?\u2026]+(?:\s|$)');
  static final _contractionRe = RegExp(r"\w+'(?:[A-Za-z]+)|\w+\u2019[A-Za-z]+");
  static final _passiveRe = RegExp(
    r'\b(is|are|was|were|be|been|being)\s+(?:\w+ly\s+)?'
    r'(\w+ed|made|given|taken|done|seen|held|known|shown|found|built|written|'
    r'driven|kept|used|based|designed|intended|considered|associated|involved|'
    r'created|developed|provided|required|allowed|caused|limited|prepared|'
    r'published|recognised|recognized|described|defined|established|drawn|grown)\b',
    caseSensitive: false,
  );

  /// Analyses [text] and returns the full report. Never throws; empty input
  /// yields a zero-score report with no triggers.
  static AiDetectorReport analyze(String text) {
    final wordCount = _wordRe.allMatches(text).length;
    if (wordCount == 0) {
      return const AiDetectorReport(
        score: 0,
        wordCount: 0,
        sentenceCount: 0,
        avgSentenceWords: 0,
        triggers: [],
      );
    }

    final sentences = _splitSentences(text);
    final sentenceWords =
        sentences.map(_countWords).where((n) => n > 0).toList();
    final lower = text.toLowerCase();
    final per1k = 1000 / wordCount;

    final claude = _claudeCheck(text);
    final triggers = <AiTrigger>[
      claude.trigger,
      _burstiness(sentenceWords),
      _phraseCheck(lower, per1k),
      _sentenceExtremes(sentenceWords),
      _contractions(text, per1k),
      _personalVoice(text, wordCount, per1k),
      _paragraphUniformity(text),
      _chatFormatting(text),
      _contrastConstructions(text, per1k),
      _openers(sentences),
      _emDashes(text, wordCount),
      _passiveVoice(text, wordCount),
      _repeatedOpeners(sentences),
    ];

    // Two scales, because the checks answer two different questions.
    //
    // The two-sided checks measure *rhythm*: sentence-length spread,
    // paragraph spread, contractions, register. A text genuinely can read
    // human on these, so they average both ways and set the style score.
    //
    // The one-way checks look for things only generated text tends to
    // carry — a stock phrase, chat formatting, a watermark. Finding none of
    // them is not evidence of a human hand, so they never vote downwards;
    // they only ever add. That asymmetry is the whole point: previously a
    // text with no em dashes, no passive voice and no connective openers
    // collected three full-weight "human" votes for the crime of not
    // containing three specific tics, which is how fully generated prose
    // that maxed out every real signal still came out at "mixed".
    const twoSidedWeights = <String, double>{
      'burstiness': 30,
      'extremes': 16,
      'paragraphs': 16,
      'contractions': 14,
      'voice': 10,
    };
    const oneWayWeights = <String, double>{
      'claude': 22,
      'phrases': 25,
      'formatting': 15,
      'contrast': 16,
      'openers': 10,
      'em-dash': 8,
      'repeated-openers': 8,
      'passive': 6,
    };

    var baseWeight = 0.0;
    var baseSum = 0.0;
    var boostSum = 0.0;
    for (final t in triggers) {
      final twoSided = twoSidedWeights[t.id];
      if (twoSided != null) {
        // A check without enough sample stays out of the average entirely
        // rather than voting "human" by default.
        if (t.strength == 0 && t.detail.startsWith('Needs')) continue;
        baseWeight += twoSided;
        baseSum += twoSided * t.strength;
        continue;
      }
      final oneWay = oneWayWeights[t.id];
      if (oneWay != null) boostSum += oneWay * t.strength;
    }

    // Style and evidence are combined the way independent suspicions
    // combine, not by splitting a fixed budget between them: either can
    // carry the verdict alone, and together they reinforce. Splitting would
    // cap a bulleted chat answer with an "I hope this helps" sign-off at a
    // middling score just because its prose rhythm was unmeasurable.
    final base = baseWeight == 0 ? 0.0 : baseSum / baseWeight;
    final style = _styleCeiling / 100 * base;
    final evidence = (boostSum / _boostSaturation).clamp(0.0, 1.0);
    var score = 100 * (1 - (1 - style) * (1 - evidence));
    // A signature outranks every style statistic beneath it: no amount of
    // human-looking rhythm changes what the text says about itself.
    if (claude.signed) score = math.max(score, 90);

    return AiDetectorReport(
      score: score.clamp(0, 100),
      wordCount: wordCount,
      sentenceCount: sentenceWords.length,
      avgSentenceWords:
          sentenceWords.isEmpty ? 0 : wordCount / sentenceWords.length,
      triggers: triggers,
      highlights: _collectHighlights(text),
      author: claude.signed ? AiAuthor.claude : AiAuthor.unknown,
    );
  }

  // ---- individual checks ----------------------------------------------------

  /// The one check that can name a model instead of describing a style.
  ///
  /// Two kinds of evidence count, and both live in the text itself rather
  /// than in its statistics:
  ///
  /// * **Invisible characters.** Zero-width joiners, word joiners, soft
  ///   hyphens and Unicode tag characters render as nothing, survive copy and
  ///   paste, and are exactly what a text watermark has to be built out of.
  ///   A keyboard does not emit them; a generator does. This is what luma
  ///   reads as the Claude watermark.
  /// * **A self-reference.** The text names Claude or Anthropic in a product
  ///   context, or carries a chat model's giveaway boilerplate.
  ///
  /// Either one flips the report to a named attribution. Their absence proves
  /// nothing - see the note in [analyze] on why a quiet scan does not vote
  /// the score down.
  static ({AiTrigger trigger, bool signed}) _claudeCheck(String text) {
    final hidden = <String, int>{};
    final it = text.runes.iterator;
    while (it.moveNext()) {
      final name = _invisibleName(it.current);
      if (name != null) hidden[name] = (hidden[name] ?? 0) + 1;
    }
    final hiddenTotal = hidden.values.fold(0, (a, b) => a + b);
    final tags = hidden['Unicode tag character'] ?? 0;

    // One tag character is conclusive on its own - that block exists for
    // nothing but hiding data. The ordinary zero-width marks do turn up as
    // stray artefacts in copied web text, so they need either a run of them
    // or two different kinds before they mean anything.
    final watermarked = tags > 0 || hiddenTotal >= 3 || hidden.length >= 2;

    final named = <String, int>{};
    _claudeRes.forEach((label, re) {
      final n = re.allMatches(text).length;
      if (n > 0) named[label] = n;
    });

    final boilerplate = <String, int>{};
    _assistantRes.forEach((label, re) {
      final n = re.allMatches(text).length;
      if (n > 0) boilerplate[label] = n;
    });

    final signed = watermarked || named.isNotEmpty;
    // One stock disclaimer is suggestive; several distinct ones are what a
    // chat transcript looks like and little else does.
    final strength = signed
        ? 1.0
        : switch (boilerplate.length) {
            0 => 0.0,
            1 => 0.5,
            2 => 0.75,
            _ => 1.0,
          };

    final String title;
    final String detail;
    if (watermarked) {
      title = 'Claude watermark found';
      detail = 'The text carries $hiddenTotal invisible '
          'character${hiddenTotal == 1 ? '' : 's'} that take up no space on '
          'screen but travel with the text through every copy and paste. '
          'Typing cannot produce them. luma reads that hidden payload as '
          'Claude’s watermark, which is why the verdict names Claude '
          'instead of hedging at "AI-generated".';
    } else if (named.isNotEmpty) {
      title = 'Claude signature in the text';
      detail = 'The text identifies its own author — it names Claude or '
          'Anthropic in a product context, not as an ordinary person’s '
          'name. That is a direct attribution, so it outranks every style '
          'statistic below it.';
    } else if (boilerplate.isNotEmpty) {
      title = 'Assistant boilerplate';
      detail = 'Stock chat-assistant phrasing shows the text came out of a '
          'conversation with a model. It does not say which model, so the '
          'verdict stays unnamed — this only raises the score.';
    } else {
      title = 'No Claude watermark';
      detail = 'No invisible watermark characters and no self-reference to '
          'Claude. That is not a clean bill of health: plenty of generated '
          'text carries no signature at all, so the style checks below still '
          'do the work.';
    }

    return (
      trigger: AiTrigger(
        id: 'claude',
        title: title,
        detail: detail,
        strength: strength,
        oneWay: true,
        evidence: [
          for (final e in hidden.entries)
            '${e.key} ×${e.value} (hidden)',
          for (final e in named.entries) '${e.key} ×${e.value}',
          for (final e in boilerplate.entries) '${e.key} ×${e.value}',
          if (hidden.isEmpty && named.isEmpty && boilerplate.isEmpty)
            'no hidden characters, no signature',
        ],
      ),
      signed: signed,
    );
  }

  /// Names the invisible code point at [cp], or null if it renders normally.
  static String? _invisibleName(int cp) {
    final named = _invisible[cp];
    if (named != null) return named;
    if (cp >= 0xE0000 && cp <= 0xE007F) return 'Unicode tag character';
    if ((cp >= 0xFE00 && cp <= 0xFE0F) || (cp >= 0xE0100 && cp <= 0xE01EF)) {
      return 'variation selector';
    }
    return null;
  }


  /// Humans write in bursts — a five-word jab after a forty-word ramble.
  /// Models settle into a comfortable middle and stay there, so a low
  /// coefficient of variation in sentence length is the strongest style tell.
  static AiTrigger _burstiness(List<int> sentenceWords) {
    if (sentenceWords.length < 6) {
      return const AiTrigger(
        id: 'burstiness',
        title: 'Uniform sentence lengths',
        detail: 'Needs at least six sentences to measure.',
        strength: 0,
      );
    }
    // Measured on real samples: generated prose clusters around 0.25-0.35,
    // human prose around 0.45-0.75. The old 0.55/0.40 window put a textbook
    // machine-uniform 0.29 at two thirds strength instead of the top.
    final cv = _coefficientOfVariation(sentenceWords);
    final strength = ((0.60 - cv) / 0.32).clamp(0.0, 1.0);
    final min = sentenceWords.reduce((a, b) => a < b ? a : b);
    final max = sentenceWords.reduce((a, b) => a > b ? a : b);
    return AiTrigger(
      id: 'burstiness',
      title: strength >= 0.5
          ? 'Very uniform sentence lengths'
          : 'Sentence-length variety',
      detail: strength >= 0.15
          ? 'Every sentence hovers around the same length. Human writing '
              'usually swings between short punches and long rambles; steady '
              'lengths suggest one generator keeping a consistent rhythm.'
          : 'Sentence lengths vary naturally, which human writers do and '
              'models find hard to fake.',
      strength: strength,
      evidence: [
        'sentences range $min\u2013$max words',
        'variation index ${cv.toStringAsFixed(2)} (low = uniform)',
      ],
    );
  }

  /// Raw buzzword counting. One hit proves nothing — "not only" is perfectly
  /// human — but dense clusters of these are where generated text gives
  /// itself away most visibly.
  /// Weighted by how exclusive each phrase is: a "delve into" counts as a
  /// whole hit, a "comprehensive" as a fraction, because people write that
  /// too. Requiring ten hits per thousand words to max out \u2014 the old rate \u2014
  /// meant a real essay carrying one "in conclusion" registered almost
  /// nothing, so the bar is now six weighted hits.
  static AiTrigger _phraseCheck(String lower, double per1k) {
    final found = <String, int>{};
    var weighted = 0.0;
    _phraseRes.forEach((phrase, re) {
      final count = re.allMatches(lower).length;
      if (count == 0) return;
      found[phrase] = count;
      weighted += count * (_strongPhraseSet.contains(phrase) ? 1.0 : 0.4);
    });
    final hits = found.values.fold(0, (a, b) => a + b);
    final rate = weighted * per1k;
    final strength = (rate / 6).clamp(0.0, 1.0);
    final ranked = found.keys.toList()
      ..sort((a, b) {
        final strong = (_strongPhraseSet.contains(b) ? 1 : 0)
            .compareTo(_strongPhraseSet.contains(a) ? 1 : 0);
        return strong != 0 ? strong : found[b]!.compareTo(found[a]!);
      });
    return AiTrigger(
      id: 'phrases',
      title: strength >= 0.15
          ? 'AI-favourite phrases'
          : 'No AI-favourite phrasing',
      detail: strength >= 0.15
          ? 'These words and constructions appear far more often in '
              'model-generated prose than in everyday human writing. Each '
              'chip below is a literal match in your text.'
          : 'None of the stock phrases models lean on were found. That is '
              'not a point in the text\u2019s favour \u2014 plenty of generated '
              'writing avoids them \u2014 so this check abstains rather than '
              'voting the score down.',
      strength: strength,
      oneWay: true,
      evidence: [
        for (final p in ranked.take(8))
          '\u201C$p\u201D \u00D7${found[p]}'
              '${_strongPhraseSet.contains(p) ? '' : ' (soft)'}',
        if (found.isEmpty) 'no matches',
        if (found.isNotEmpty)
          '$hits match${hits == 1 ? '' : 'es'}, '
              '${rate.toStringAsFixed(1)} weighted per 1000 words',
      ],
    );
  }

  /// Human sentence length has outliers at both ends: the four-word aside,
  /// the thirty-five-word run-on. Generated prose lives in the comfortable
  /// middle and produces neither. This catches what [_burstiness] misses \u2014
  /// a text can show a respectable spread and still contain no genuinely
  /// short or long sentence anywhere in it.
  static AiTrigger _sentenceExtremes(List<int> sentenceWords) {
    if (sentenceWords.length < 8) {
      return const AiTrigger(
        id: 'extremes',
        title: 'Sentence-length extremes',
        detail: 'Needs at least eight sentences to measure.',
        strength: 0,
      );
    }
    final short = sentenceWords.where((n) => n <= 5).length;
    final long = sentenceWords.where((n) => n >= 28).length;
    final n = sentenceWords.length;
    // Either extreme on its own clears the check: a clipped, chatty voice
    // with no long sentences is every bit as human as a rambling one with
    // no short ones. Only a text with neither is suspicious.
    final variety = math.min(1.0, (short / n) / 0.12 + (long / n) / 0.10);
    final strength = (1 - variety).clamp(0.0, 1.0);
    return AiTrigger(
      id: 'extremes',
      title: strength >= 0.15
          ? 'No short or long sentences'
          : 'Sentence lengths reach both extremes',
      detail: strength >= 0.15
          ? 'Not one sentence is genuinely short and not one genuinely runs '
              'on. People write both without thinking about it; a generator '
              'settles into a safe middle band and stays there.'
          : 'The text contains both clipped sentences and long ones, the '
              'way unedited human writing usually does.',
      strength: strength,
      evidence: [
        '$short of $n sentences under 6 words',
        '$long of $n sentences over 27 words',
      ],
    );
  }

  /// Whether a person is visibly on the page: first- and second-person
  /// pronouns, casual register, direct questions. Their absence is real
  /// evidence but noisy \u2014 encyclopaedic and academic humans write
  /// impersonally too \u2014 hence the modest weight.
  static AiTrigger _personalVoice(String text, int wordCount, double per1k) {
    if (wordCount < 120) {
      return const AiTrigger(
        id: 'voice',
        title: 'Impersonal register',
        detail: 'Needs at least 120 words to measure.',
        strength: 0,
      );
    }
    var pronouns = 0;
    var informal = 0;
    for (final m in _wordRe.allMatches(text)) {
      final w = m.group(0)!.toLowerCase();
      if (_personalPronouns.contains(w)) pronouns++;
      if (_informalWords.contains(w)) informal++;
    }
    final questions = '?'.allMatches(text).length;
    final rate = (pronouns + 1.5 * informal + 2.0 * questions) * per1k;
    final strength = ((14 - rate) / 14).clamp(0.0, 1.0);
    return AiTrigger(
      id: 'voice',
      title: strength >= 0.15 ? 'Impersonal register' : 'Personal register',
      detail: strength >= 0.15
          ? 'Nobody is on the page \u2014 barely an "I", "we" or "you", no '
              'casual wording, no direct questions. Generated prose defaults '
              'to this detached register. Formal human writing does too, '
              'which is why this counts for less than the rhythm checks.'
          : 'The text speaks in a personal voice, with pronouns and casual '
              'wording that generated prose rarely reaches for unprompted.',
      strength: strength,
      evidence: [
        '$pronouns personal pronouns, $informal casual words, '
            '$questions question${questions == 1 ? '' : 's'}',
        '${rate.toStringAsFixed(1)} per 1000 words (low = impersonal)',
      ],
    );
  }

  /// Chat models format almost every answer the same way: a heading, a run
  /// of bullets, bolded labels followed by a colon. Pasted into a document
  /// that scaffolding travels with the text, and it is very hard to produce
  /// by accident.
  static AiTrigger _chatFormatting(String text) {
    final lines = text.split('\n').where((l) => l.trim().isNotEmpty).toList();
    if (lines.length < 6) {
      return const AiTrigger(
        id: 'formatting',
        title: 'Chat-answer formatting',
        detail: 'Needs at least six lines to measure.',
        strength: 0,
        oneWay: true,
      );
    }
    final headings = _headingRe.allMatches(text).length;
    final bullets = _bulletRe.allMatches(text).length;
    final boldLeads = _boldLeadRe.allMatches(text).length;
    final labelLeads = _labelLeadRe.allMatches(text).length;
    final scaffold = math.min(
      lines.length,
      headings + bullets + boldLeads + labelLeads,
    );
    var strength = 0.0;
    if (scaffold >= 3) {
      strength = (scaffold / lines.length / 0.45).clamp(0.0, 1.0);
    }
    // Bolded labels and markdown headings are the chat-window tell in
    // particular, so a couple of them carry weight on their own.
    if (boldLeads >= 2 || headings >= 2) {
      strength = math.max(strength, 0.65);
    }
    return AiTrigger(
      id: 'formatting',
      title: strength >= 0.15
          ? 'Chat-answer formatting'
          : 'No chat-answer formatting',
      detail: strength >= 0.15
          ? 'The text is laid out the way a chat model answers: headings, '
              'bullet runs and bolded labels. That structure travels with '
              'the text when it is pasted somewhere else.'
          : 'The text reads as prose rather than a formatted chat answer. '
              'Plenty of generated text is prose too, so this only counts '
              'when it fires.',
      strength: strength,
      oneWay: true,
      evidence: [
        if (headings > 0)
          '$headings markdown heading${headings == 1 ? '' : 's'}',
        if (bullets > 0)
          '$bullets bullet or numbered line${bullets == 1 ? '' : 's'}',
        if (boldLeads > 0)
          '$boldLeads bolded lead-in${boldLeads == 1 ? '' : 's'}',
        if (labelLeads > 0)
          '$labelLeads "Label: text" line${labelLeads == 1 ? '' : 's'}',
        if (scaffold == 0) 'plain prose, no list scaffolding',
        if (scaffold > 0) '$scaffold of ${lines.length} lines are scaffolding',
      ],
    );
  }

  /// The corrective-contrast habit: "not just X, but Y", "it's not about
  /// this. It's about that", the staged reveal of the "real" question.
  /// Current models reach for these constantly when asked to sound
  /// insightful, and they survive the paraphrasing that defeats the
  /// vocabulary checks.
  static AiTrigger _contrastConstructions(String text, double per1k) {
    final found = <String, int>{};
    _contrastRes.forEach((label, re) {
      final n = re.allMatches(text).length;
      if (n > 0) found[label] = n;
    });
    final hits = found.values.fold(0, (a, b) => a + b);
    final rate = hits * per1k;
    final strength = (rate / 4).clamp(0.0, 1.0);
    return AiTrigger(
      id: 'contrast',
      title: strength >= 0.15
          ? 'Corrective-contrast constructions'
          : 'No corrective-contrast habit',
      detail: strength >= 0.15
          ? 'Sentences that set up a wrong answer only to knock it down '
              '\u2014 "not just X, but Y", "the real question is" \u2014 are the '
              'rhetorical move current models use to sound insightful.'
          : 'None of the set-up-and-knock-down constructions models favour '
              'were found. Their absence means nothing on its own.',
      strength: strength,
      oneWay: true,
      evidence: [
        for (final e in found.entries) '${e.key} \u00D7${e.value}',
        if (found.isEmpty) 'none found',
        if (found.isNotEmpty) '${rate.toStringAsFixed(1)} per 1000 words',
      ],
    );
  }

  /// Models open paragraph after paragraph with a tidy connective. Humans do
  /// it too, just nowhere near as consistently.
  static AiTrigger _openers(List<String> sentences) {
    if (sentences.length < 6) {
      return const AiTrigger(
        id: 'openers',
        title: 'Transition-word openers',
        detail: 'Needs at least six sentences to measure.',
        strength: 0,
        oneWay: true,
      );
    }
    final counts = <String, int>{};
    var used = 0;
    for (final s in sentences) {
      final firstWord = _wordRe.firstMatch(s.toLowerCase())?.group(0);
      if (firstWord != null && _connectives.contains(firstWord)) {
        used++;
        counts[firstWord] = (counts[firstWord] ?? 0) + 1;
      }
    }
    final ratio = used / sentences.length;
    final strength = ((ratio - 0.05) / 0.18).clamp(0.0, 1.0);
    final ranked = counts.keys.toList()
      ..sort((a, b) => counts[b]!.compareTo(counts[a]!));
    return AiTrigger(
      id: 'openers',
      title: 'Transition-word openers',
      detail: strength >= 0.15
          ? '$used of ${sentences.length} sentences start with a formal '
              'connective. Essay-bot structure opens sections with '
              '"Moreover," and "Furthermore," far more than people do.'
          : 'Sentences do not lean on formal connectives to start. That on '
              'its own says nothing about who wrote them.',
      strength: strength,
      oneWay: true,
      evidence: [
        for (final w in ranked.take(6))
          '$w \u00D7${counts[w]} at sentence start',
        if (ranked.isEmpty) 'none used',
      ],
    );
  }

  /// People contract. Models mostly don't — training rewards the spelled-out
  /// formal form. A long text without a single "don't" or "it's" is quietly
  /// suspicious (though formal human writing looks the same, hence the low
  /// weight).
  static AiTrigger _contractions(String text, double per1k) {
    final wordCount = _wordRe.allMatches(text).length;
    if (wordCount < 120) {
      return const AiTrigger(
        id: 'contractions',
        title: 'Missing contractions',
        detail: 'Needs at least 120 words to measure.',
        strength: 0,
      );
    }
    final contractions = _contractionRe.allMatches(text).length;
    final rate = contractions * per1k;
    final strength = ((1.5 - rate) / 1.5).clamp(0.0, 1.0);
    return AiTrigger(
      id: 'contractions',
      title: rate < 1.5 ? 'Missing contractions' : 'Natural contraction use',
      detail: rate < 1.5
          ? 'Almost no contracted forms ("don\u2019t", "it\u2019s"). Generated '
              'text defaults to the stiffer un-contracted register.'
          : 'Contractions appear at a natural human rate.',
      strength: strength,
      evidence: [
        '$contractions contraction${contractions == 1 ? '' : 's'} in $wordCount words',
      ],
    );
  }

  /// The em dash is the punctuation mark models reached for so often it
  /// became a meme. Rate matters more than presence, and the text has to be
  /// long enough that one dash doesn't inflate into a "rate".
  static AiTrigger _emDashes(String text, int wordCount) {
    final dashes = '\u2014'.allMatches(text).length + '--'.allMatches(text).length;
    if (wordCount < 150) {
      return const AiTrigger(
        id: 'em-dash',
        title: 'Em-dash overuse',
        detail: 'Needs at least 150 words to measure.',
        strength: 0,
        oneWay: true,
      );
    }
    if (dashes == 0) {
      return const AiTrigger(
        id: 'em-dash',
        title: 'Em-dash overuse',
        detail: 'No em dashes present, which proves nothing either way.',
        strength: 0,
        oneWay: true,
      );
    }
    final rate = dashes * (1000 / wordCount);
    final strength = ((rate - 2.0) / 6.0).clamp(0.0, 1.0);
    return AiTrigger(
      id: 'em-dash',
      title: 'Em-dash overuse',
      detail: strength >= 0.15
          ? 'Em dashes pepper the text well past what typical human prose '
              'uses \u2014 a much-memed model habit.'
          : 'Em-dash use is within normal range.',
      strength: strength,
      oneWay: true,
      evidence: [
        '$dashes em dashes (${rate.toStringAsFixed(1)} per 1000 words)',
      ],
    );
  }

  /// Formal, passive-heavy register is another trained-in habit. Weak signal
  /// on its own \u2014 legal and academic humans write this way too \u2014 but it
  /// corroborates the other checks.
  static AiTrigger _passiveVoice(String text, int wordCount) {
    if (wordCount < 100) {
      return const AiTrigger(
        id: 'passive',
        title: 'Passive-voice density',
        detail: 'Needs at least 100 words to measure.',
        strength: 0,
        oneWay: true,
      );
    }
    final matches = _passiveRe.allMatches(text).length;
    final rate = 100 * matches / wordCount;
    final strength = ((rate - 6) / 14).clamp(0.0, 1.0);
    return AiTrigger(
      id: 'passive',
      title: 'Passive-voice density',
      detail: strength >= 0.15
          ? 'Heavy passive construction ("was designed to", "is considered") '
              'keeps agency out of sentences \u2014 common in generated prose.'
          : 'Passive voice stays at a normal level, which is true of most '
              'generated text as well.',
      strength: strength,
      oneWay: true,
      evidence: [
        '$matches passive constructions (${rate.toStringAsFixed(1)} per 100 words)',
      ],
    );
  }

  /// Generated essays come in near-equal blocks. Humans produce a two-line
  /// paragraph followed by a ten-line monster.
  static AiTrigger _paragraphUniformity(String text) {
    final paragraphs = text
        .split(RegExp(r'\r?\n\s*\r?\n'))
        .map(_countWords)
        .where((n) => n > 0)
        .toList();
    if (paragraphs.length < 3) {
      return const AiTrigger(
        id: 'paragraphs',
        title: 'Uniform paragraphs',
        detail: 'Needs at least three paragraphs to measure.',
        strength: 0,
      );
    }
    final cv = _coefficientOfVariation(paragraphs);
    final strength = ((0.50 - cv) / 0.35).clamp(0.0, 1.0);
    return AiTrigger(
      id: 'paragraphs',
      title: strength >= 0.15 ? 'Uniform paragraphs' : 'Varied paragraphs',
      detail: strength >= 0.15
          ? 'All paragraphs are nearly the same size, like content poured '
              'evenly into containers. Human drafts lurch between short and '
              'long.'
          : 'Paragraph sizes differ naturally.',
      strength: strength,
      evidence: [
        '${paragraphs.length} paragraphs: '
            '${paragraphs.map((p) => '${p}w').join(', ')}',
      ],
    );
  }

  /// Same opening word again and again (beyond ordinary stopwords) points at
  /// templated generation rather than a person reaching for variety.
  static AiTrigger _repeatedOpeners(List<String> sentences) {
    if (sentences.length < 8) {
      return const AiTrigger(
        id: 'repeated-openers',
        title: 'Repeated sentence openers',
        detail: 'Needs at least eight sentences to measure.',
        strength: 0,
        oneWay: true,
      );
    }
    final counts = <String, int>{};
    for (final s in sentences) {
      final first = _wordRe.firstMatch(s.toLowerCase())?.group(0);
      if (first == null || _openerStopwords.contains(first)) continue;
      counts[first] = (counts[first] ?? 0) + 1;
    }
    String best = '';
    var bestCount = 0;
    for (final entry in counts.entries) {
      if (entry.value > bestCount) {
        best = entry.key;
        bestCount = entry.value;
      }
    }
    if (best.isEmpty) {
      return const AiTrigger(
        id: 'repeated-openers',
        title: 'Repeated sentence openers',
        detail: 'Not enough distinctive sentence starts to measure.',
        strength: 0,
        oneWay: true,
      );
    }
    final share = bestCount / sentences.length;
    final strength = ((share - 0.18) / 0.27).clamp(0.0, 1.0);
    return AiTrigger(
      id: 'repeated-openers',
      title: 'Repeated sentence openers',
      detail: strength >= 0.15
          ? '"$best" opens $bestCount sentences. Real writers rarely hammer '
              'one opener; template-driven generation does.'
          : 'Sentence openers are varied, as they are in most writing of '
              'either origin.',
      strength: strength,
      oneWay: true,
      evidence: ['"$best" starts $bestCount of ${sentences.length} sentences'],
    );
  }

  // ---- highlighting ---------------------------------------------------------

  /// Walks the text once per signal and records the exact stretch each one
  /// matched, so the report can paint the evidence in place instead of only
  /// describing it. Overlapping flags merge, with the more conclusive kind
  /// winning the merged span.
  static List<AiHighlight> _collectHighlights(String text) {
    final raw = <AiHighlight>[];

    _phraseRes.forEach((phrase, re) {
      for (final m in re.allMatches(text)) {
        raw.add(AiHighlight(
          start: m.start,
          end: m.end,
          kind: AiHighlightKind.phrase,
          note: 'Stock LLM phrase “$phrase”',
        ));
      }
    });

    _contrastRes.forEach((label, re) {
      for (final m in re.allMatches(text)) {
        raw.add(AiHighlight(
          start: m.start,
          end: m.end,
          kind: AiHighlightKind.phrase,
          note: 'Corrective contrast: $label',
        ));
      }
    });

    _claudeRes.forEach((label, re) {
      for (final m in re.allMatches(text)) {
        raw.add(AiHighlight(
          start: m.start,
          end: m.end,
          kind: AiHighlightKind.claudeName,
          note: label,
        ));
      }
    });

    _assistantRes.forEach((label, re) {
      for (final m in re.allMatches(text)) {
        raw.add(AiHighlight(
          start: m.start,
          end: m.end,
          kind: AiHighlightKind.assistant,
          note: label,
        ));
      }
    });

    for (final m in _passiveRe.allMatches(text)) {
      raw.add(AiHighlight(
        start: m.start,
        end: m.end,
        kind: AiHighlightKind.passive,
        note: 'Passive construction',
      ));
    }

    for (final sentence in _sentenceSpans(text)) {
      final m = _wordRe.firstMatch(sentence.text);
      if (m == null) continue;
      final word = m.group(0)!.toLowerCase();
      if (!_connectives.contains(word)) continue;
      raw.add(AiHighlight(
        start: sentence.start + m.start,
        end: sentence.start + m.end,
        kind: AiHighlightKind.opener,
        note: 'Sentence opens with “$word”',
      ));
    }

    for (var i = 0; i < text.length; i++) {
      if (text.codeUnitAt(i) == 0x2014) {
        raw.add(AiHighlight(
          start: i,
          end: i + 1,
          kind: AiHighlightKind.emDash,
          note: 'Em dash',
        ));
      }
    }

    final runes = text.runes.iterator;
    while (runes.moveNext()) {
      final name = _invisibleName(runes.current);
      if (name == null) continue;
      final start = runes.rawIndex;
      final span = _paintable(text, start, start + runes.currentSize);
      raw.add(AiHighlight(
        start: span.$1,
        end: span.$2,
        kind: AiHighlightKind.watermark,
        note: 'Hidden $name inside this word',
      ));
    }

    return _mergeHighlights(raw);
  }

  /// An invisible character has no width of its own, so its highlight is
  /// stretched over the word it hides inside. When it sits alone between
  /// spaces one neighbouring character is borrowed instead, so the reader
  /// still gets a mark to look at.
  static (int, int) _paintable(String text, int start, int end) {
    var s = start;
    var e = end;
    while (s > 0 && !_isSpace(text.codeUnitAt(s - 1)) && start - s < 24) {
      s--;
    }
    while (e < text.length && !_isSpace(text.codeUnitAt(e)) && e - end < 24) {
      e++;
    }
    if (s == start && e == end) {
      s = math.max(0, s - 1);
      e = math.min(text.length, e + 1);
    }
    return (s, e);
  }

  static bool _isSpace(int unit) =>
      unit == 0x20 || unit == 0x0A || unit == 0x0D || unit == 0x09;

  /// Sorts, merges and caps the raw flags, so the reader never sees one
  /// highlight split mid-word by a weaker signal sitting underneath it.
  static List<AiHighlight> _mergeHighlights(List<AiHighlight> raw) {
    if (raw.isEmpty) return const [];
    raw.sort((a, b) => a.start != b.start
        ? a.start.compareTo(b.start)
        : b.end.compareTo(a.end));
    final out = <AiHighlight>[];
    for (final h in raw) {
      if (out.isEmpty || h.start >= out.last.end) {
        out.add(h);
        continue;
      }
      final last = out.last;
      final stronger = h.kind.severity > last.kind.severity ? h : last;
      out[out.length - 1] = AiHighlight(
        start: last.start,
        end: math.max(last.end, h.end),
        kind: stronger.kind,
        note: stronger.note,
      );
    }
    // A pathological paste should not become tens of thousands of spans.
    return out.length > _maxHighlights ? out.sublist(0, _maxHighlights) : out;
  }

  static const _maxHighlights = 400;

  // ---- helpers --------------------------------------------------------------

  static List<String> _splitSentences(String text) => text
      .split(_sentenceSplitRe)
      .map((s) => s.trim())
      .where((s) => _countWords(s) > 0)
      .toList();

  /// The same split as [_splitSentences], but keeping each sentence's offset
  /// in the original text so a highlight can point back at it.
  static List<({int start, String text})> _sentenceSpans(String text) {
    final out = <({int start, String text})>[];
    var cursor = 0;
    void add(int start, String chunk) {
      if (_countWords(chunk) > 0) out.add((start: start, text: chunk));
    }

    for (final m in _sentenceSplitRe.allMatches(text)) {
      add(cursor, text.substring(cursor, m.end));
      cursor = m.end;
    }
    if (cursor < text.length) add(cursor, text.substring(cursor));
    return out;
  }

  static int _countWords(String text) => _wordRe.allMatches(text).length;

  static double _coefficientOfVariation(List<int> values) {
    final n = values.length;
    final mean = values.fold<int>(0, (a, b) => a + b) / n;
    if (mean == 0) return 0;
    final variance =
        values.fold<double>(0, (a, b) => a + (b - mean) * (b - mean)) / n;
    return variance <= 0 ? 0 : math.sqrt(variance) / mean;
  }
}
