import puppeteer from 'puppeteer-core';
const sleep = (ms) => new Promise((r) => setTimeout(r, ms));
const browser = await puppeteer.launch({ executablePath: 'C:/Program Files (x86)/Microsoft/Edge/Application/153.0.4234.48/msedge.exe', headless: true, pipe: true, args: ['--no-sandbox','--enable-unsafe-swiftshader','--use-angle=swiftshader'] });
const page = await browser.newPage();
await page.setViewport({ width: 1400, height: 950 });
const logs = [];
page.on('console', (m) => logs.push(m.type() + ': ' + m.text()));
page.on('response', (r) => { if (r.status() >= 400) logs.push('HTTP ' + r.status() + ' ' + r.url()); });
page.on('pageerror', (e) => logs.push('pageerror: ' + e));
await page.goto('http://localhost:8131/admin?key=local-admin-key', { waitUntil: 'load' });
await page.evaluate(() => document.getElementById('bannersCatalogBtn').click());
await page.waitForFunction(() => document.querySelectorAll('.bn-tile').length > 0);
await page.evaluate((id) => document.querySelector('[data-frame="' + id + '"]').click(), process.argv[2] || 'pagoda_haiku45');
await sleep(25000);
console.log('stage msg:', await page.$eval('#bnStageMsg', (e) => e.hidden ? '(hidden)' : e.textContent));
console.log('rects:', JSON.stringify(await page.evaluate(() => ['bnFramer', 'bnStageWrap', 'bnStage', 'bnSceneFrame'].map((id) => { const el = document.getElementById(id); const r = el.getBoundingClientRect(); const cs = getComputedStyle(el); return id + ' ' + Math.round(r.width) + 'x' + Math.round(r.height) + ' ' + cs.display + ' w=' + cs.width + ' h=' + cs.height + ' tf=' + cs.transform; }))));
console.log('frames:', page.frames().map((f) => f.url()));
const f = page.frames().find((x) => x.url().includes('/scene/'));
if (f) console.log('inside:', JSON.stringify(await f.evaluate(() => ({ shot: typeof window.__lumaShot, dev: typeof window.__THREE_DEVTOOLS__, canvases: document.querySelectorAll('canvas').length, w: innerWidth, h: innerHeight, head: document.head.innerHTML.slice(0, 120) }))));
console.log(logs.slice(0, 15).join('\n'));
await browser.close();
